(function(){
  if(window.MF885_COMMUNITY_CANARY)return;
  var marker='MF885 Community Canary Logs 0.0-logs-r1',events=[],sequence=0,paused=false,pollBusy=false,maxEvents=200;
  window.MF885_COMMUNITY_CANARY={id:'0.0-logs-r1',kind:'webui-logs',marker:marker};
  var css='#zmiDbgToggle{position:fixed;right:10px;bottom:10px;z-index:2147483646;border:1px solid #466b86;border-radius:4px;padding:7px 10px;background:#17384d;color:#fff;font:bold 12px Arial,sans-serif;box-shadow:0 2px 8px #0008;cursor:pointer}#zmiDbgPanel{display:none;position:fixed;z-index:2147483647;left:8px;right:8px;top:8px;bottom:8px;padding:0;background:#f5f7f8;color:#1b2730;border:1px solid #607d8b;box-shadow:0 4px 24px #000a;font:12px/1.35 Arial,sans-serif;text-align:left}#zmiDbgPanel.open{display:flex;flex-direction:column}#zmiDbgPanel *{box-sizing:border-box}#zmiDbgPanel header{display:flex;align-items:center;gap:6px;padding:8px;background:#24485e;color:#fff}#zmiDbgPanel header b{margin-right:auto}#zmiDbgPanel button,#zmiDbgPanel input{font:12px Arial,sans-serif}#zmiDbgPanel button{padding:4px 7px;border:1px solid #78909c;background:#fff;color:#263238;border-radius:3px;cursor:pointer}#zmiDbgPanel input{width:180px;max-width:32vw;padding:4px;border:1px solid #90a4ae}#zmiDbgMeta{padding:5px 8px;border-bottom:1px solid #cfd8dc;background:#e8eef1;color:#455a64}#zmiDbgList{flex:1;overflow:auto;padding:5px;background:#fff}#zmiDbgList article{margin:0 0 5px;padding:5px 7px;border-left:3px solid #607d8b;background:#f1f4f5}#zmiDbgList article.err{border-color:#c62828;background:#fff1f1}#zmiDbgList article.net{border-color:#0277bd}#zmiDbgList strong{font-family:monospace}#zmiDbgList time{color:#607d8b;margin-right:7px}#zmiDbgList pre{margin:4px 0 0;white-space:pre-wrap;word-break:break-all;max-height:180px;overflow:auto;color:#263238;font:11px/1.35 monospace}@media(max-width:600px){#zmiDbgPanel{left:2px;right:2px;top:2px;bottom:2px}#zmiDbgPanel header{flex-wrap:wrap}#zmiDbgPanel header b{flex-basis:100%}#zmiDbgPanel input{max-width:none;flex:1}}';
  var style=document.createElement('style');style.id='zmiCanaryLogsStyle';style.type='text/css';style.appendChild(document.createTextNode(css));(document.head||document.getElementsByTagName('head')[0]).appendChild(style);
  var toggle=document.createElement('button');toggle.type='button';toggle.id='zmiDbgToggle';toggle.title='Open live technical logs';toggle.innerHTML='Logs <span id="zmiDbgBadge">0</span>';
  var panel=document.createElement('section');panel.id='zmiDbgPanel';panel.setAttribute('aria-label','MF885 live technical logs');panel.innerHTML='<header><b>MF885 Canary Logs 0.0-logs-r1</b><input id="zmiDbgFilter" placeholder="filter"><button type="button" id="zmiDbgPause">Pause</button><button type="button" id="zmiDbgClear">Clear</button><button type="button" id="zmiDbgCopy">Copy</button><button type="button" id="zmiDbgExport">Export</button><button type="button" id="zmiDbgClose">Close</button></header><div id="zmiDbgMeta">Live XHR/fetch/forms/errors · router detailed_log every 8 s while open · SMS payloads hidden</div><div id="zmiDbgList"></div>';
  document.body.appendChild(toggle);document.body.appendChild(panel);
  function now(){try{return new Date().toISOString()}catch(e){return String(new Date())}}
  function asText(value){if(value===undefined||value===null)return'';if(typeof value==='string')return value;try{if(window.XMLSerializer&&value&&value.nodeType)return new XMLSerializer().serializeToString(value)}catch(e){}try{return JSON.stringify(value)}catch(e){return String(value)}}
  function isSms(url,body){return /(?:[?&]file=message(?:&|$)|<get_message\b|<send_message\b|<delete_message\b|<message_content\b|<content\b)/i.test(String(url||'')+' '+String(body||''))}
  function safe(value,sms){var out=asText(value),k='pass(?:word|wd)?|pwd|pin|puk|psk|wifi[-_]?(?:key|password)|token|(?:access|refresh)[-_]?token|(?:x[-_]?)?api[-_]?key|secret|client[-_]?secret|jwt|bearer|session[-_]?id|sid|nonce|cnonce|response|(?:proxy[-_]?)?auth(?:orization)?|(?:set[-_]?)?cookie|imei|imsi|iccid|serial(?:[-_]?number)?|device[-_]?(?:sn|serial)|sn|(?:current[-_]?)?device[-_]?mac|(?:wifi|lan|client)[-_]?mac|wifimac|ssid|apn|pdp[-_]?name|ip[-_]?(?:address|addr)|ipv6[-_]?addr|phone(?:[-_]?number)?|username|msisdn';if(sms&&out)return'<SMS payload hidden>';out=out.replace(/\b(?:Authorization|Proxy-Authorization|Cookie|Set-Cookie)\b\s*:\s*[^\r\n]*/gi,'<header hidden>');out=out.replace(new RegExp('<('+k+')\\b[^>]*?(?:\\/\\s*>|>[\\s\\S]*?<\\/\\1>)','gi'),'<$1><hidden></$1>');out=out.replace(new RegExp('(["\\\']?\\b(?:'+k+')["\\\']?\\s*[:=]\\s*)(?:"(?:\\\\.|[^"\\\\])*"|\\\'(?:\\\\.|[^\\\'\\\\])*\\\'|[^\\s,;&}]+)','gi'),'$1<hidden>');out=out.replace(/([?&](?:token|access[-_]?token|(?:x[-_]?)?api[-_]?key|session[-_]?id|pass(?:word|wd)?|pwd|nonce|cnonce|response)=)[^&#]*/gi,'$1<hidden>');out=out.replace(/\b[0-9a-f]{1,4}(?:(?::[0-9a-f]{0,4}){3,7}|(?::[0-9a-f]{1,4})*::[\da-f:.]*)(?=\W|$)|::[\da-f:.]*(?=\W|$)|\b(?:\d{1,3}\.){3}\d{1,3}\b|\b\d{14,20}\b|\+\d[\d ()-]{6,}\d/gi,'<hidden>');return out}
  function endpoint(url){var text=String(url||'');var match=text.match(/[?&]file=([^&#]+)/i);return match?decodeURIComponent(match[1]):text.replace(/^https?:\/\/[^/]+/i,'').slice(0,180)}
  function add(kind,title,detail){events.push({id:++sequence,at:now(),kind:kind,title:safe(title,false).slice(0,300),detail:safe(detail,false).slice(0,12000)});if(events.length>maxEvents)events.splice(0,events.length-maxEvents);badge();if(!paused)render()}
  function badge(){var el=document.getElementById('zmiDbgBadge');if(el)el.innerHTML=String(events.length)}
  function render(){var root=document.getElementById('zmiDbgList'),filter=document.getElementById('zmiDbgFilter');if(!root)return;var q=filter?String(filter.value||'').toLowerCase():'',fragment=document.createDocumentFragment();root.innerHTML='';for(var i=events.length-1;i>=0;i--){var item=events[i],hay=(item.kind+' '+item.title+' '+item.detail).toLowerCase();if(q&&hay.indexOf(q)<0)continue;var row=document.createElement('article');row.className=item.kind==='error'?'err':item.kind==='network'?'net':'';var head=document.createElement('div'),time=document.createElement('time'),strong=document.createElement('strong');time.appendChild(document.createTextNode(item.at+' #'+item.id));strong.appendChild(document.createTextNode(item.kind+' · '+item.title));head.appendChild(time);head.appendChild(strong);row.appendChild(head);if(item.detail){var pre=document.createElement('pre');pre.appendChild(document.createTextNode(item.detail));row.appendChild(pre)}fragment.appendChild(row)}root.appendChild(fragment)}
  function report(){var out=[marker,'generated='+now(),'events='+events.length,'sms_payloads=hidden',''];for(var i=0;i<events.length;i++){var e=events[i];out.push(e.at+' #'+e.id+' '+e.kind+' '+e.title);if(e.detail)out.push(e.detail);out.push('')}return out.join('\n')}
  function copyFeedback(){var button=document.getElementById('zmiDbgCopy');if(!button)return;button.innerHTML='Copied';setTimeout(function(){button.innerHTML='Copy'},1200)}
  function legacyCopy(text){var area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.left='-9999px';document.body.appendChild(area);area.select();try{document.execCommand('copy')}catch(e){}document.body.removeChild(area);copyFeedback()}
  function copy(){var text=report();if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(text).then(copyFeedback,function(){legacyCopy(text)});return}legacyCopy(text)}
  function save(){try{var blob=new Blob([report()],{type:'text/plain;charset=utf-8'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='mf885-canary-log-'+Date.now()+'.txt';document.body.appendChild(link);link.click();setTimeout(function(){URL.revokeObjectURL(link.href);document.body.removeChild(link)},0)}catch(e){add('error','log export failed',e&&e.message||e)}}
  function openPanel(){document.getElementById('zmiDbgPanel').className='open';render();pollDetailedLog()}
  function closePanel(){document.getElementById('zmiDbgPanel').className=''}
  var xhrOpen=XMLHttpRequest.prototype.open,xhrSend=XMLHttpRequest.prototype.send;
  XMLHttpRequest.prototype.open=function(method,url){this.__zmiLog={method:String(method||'GET').toUpperCase(),url:String(url||''),started:0};return xhrOpen.apply(this,arguments)};
  XMLHttpRequest.prototype.send=function(body){var self=this,meta=this.__zmiLog||{method:'?',url:'',started:0},bodyText=asText(body),sms=isSms(meta.url,bodyText);meta.started=Date.now();function done(){var elapsed=Date.now()-meta.started,response='';try{response=self.responseText||''}catch(e){response='<response unreadable>'}var detail='status='+String(self.status||0)+' duration_ms='+elapsed+' bytes='+response.length;if(bodyText)detail+='\nrequest_body='+safe(bodyText,sms);if(response)detail+='\nresponse_body='+safe(response,sms);add(self.status>=400?'error':'network',meta.method+' '+endpoint(meta.url),detail)}try{this.addEventListener('loadend',done,false);return xhrSend.apply(this,arguments)}catch(e){add('error',meta.method+' '+endpoint(meta.url),'send failed: '+safe(e&&e.message||e,false));throw e}};
  if(window.fetch){var nativeFetch=window.fetch;window.fetch=function(input,init){var url=typeof input==='string'?input:input&&input.url||'',method=init&&init.method||'GET',body=init&&init.body||'',sms=isSms(url,body),started=Date.now();return nativeFetch.apply(this,arguments).then(function(response){try{response.clone().text().then(function(text){add(response.status>=400?'error':'network',String(method).toUpperCase()+' '+endpoint(url),'status='+response.status+' duration_ms='+(Date.now()-started)+' bytes='+text.length+(body?'\nrequest_body='+safe(body,sms):'')+(text?'\nresponse_body='+safe(text,sms):''))})}catch(e){}return response},function(error){add('error',String(method).toUpperCase()+' '+endpoint(url),'fetch failed after '+(Date.now()-started)+' ms: '+safe(error&&error.message||error,false));throw error})}};
  document.addEventListener('submit',function(event){var form=event.target,names=[],elements=form&&form.elements||[];for(var i=0;i<elements.length;i++)if(elements[i].name||elements[i].id)names.push(elements[i].name||elements[i].id);add('form',String(form.method||'GET').toUpperCase()+' '+(form.action||location.pathname),'fields='+names.join(','))},true);
  document.addEventListener('click',function(event){var node=event.target;while(node&&node!==document&&!/^(A|BUTTON|INPUT)$/.test(node.tagName||''))node=node.parentNode;if(!node||node===document)return;add('ui','control',String(node.id||node.name||node.tagName).slice(0,220))},true);
  if(window.console){for(var ci=0;ci<2;ci++)(function(name){var original=window.console[name];if(typeof original!=='function')return;window.console[name]=function(){try{var value=Array.prototype.join.call(arguments,' ');add(name==='error'?'error':'console','console.'+name,isSms('',value)?'<SMS payload hidden>':value)}catch(e){}return original.apply(window.console,arguments)}})(ci?'warn':'error')}
  window.addEventListener('error',function(event){add('error','javascript',String(event.message||'error')+' @ '+String(event.filename||'')+':'+String(event.lineno||0))});
  window.addEventListener('unhandledrejection',function(event){add('error','unhandled promise',safe(event.reason&&event.reason.message||event.reason||'unknown',false))});
  function pollDetailedLog(){var panel=document.getElementById('zmiDbgPanel');if(!panel||panel.className!=='open'||pollBusy)return;pollBusy=true;var request=new XMLHttpRequest();try{request.open('GET','xml_action.cgi?method=get&module=duster&file=detailed_log',true);request.setRequestHeader('Authorization',getAuthHeader('GET'));request.onreadystatechange=function(){if(request.readyState===4)pollBusy=false};request.onerror=function(){pollBusy=false};request.send(null)}catch(e){pollBusy=false;add('error','detailed_log poll',e&&e.message||e)}}
  document.getElementById('zmiDbgToggle').onclick=openPanel;document.getElementById('zmiDbgClose').onclick=closePanel;document.getElementById('zmiDbgPause').onclick=function(){paused=!paused;this.innerHTML=paused?'Resume':'Pause';if(!paused)render()};document.getElementById('zmiDbgClear').onclick=function(){events=[];badge();render()};document.getElementById('zmiDbgCopy').onclick=copy;document.getElementById('zmiDbgExport').onclick=save;document.getElementById('zmiDbgFilter').oninput=render;
  setInterval(pollDetailedLog,8000);add('canary','loaded',marker+' · '+location.href);
})();
