/* MF885 Community R3.9 TTL module */
(function(w){
  'use strict';
  var core=w.MF885CommunityR39,READ_INTERVAL_MS=30000,sequence=0;
  var runtime={current:null,kind:null,locked:false,nextAt:0,bound:false};

  function node(id){return w.document.getElementById(id)}
  function serial(){sequence++;return 'TTL39-'+('0000'+sequence).slice(-4)}
  function log(id,kind,values){if(w.console&&typeof w.console.debug==='function')w.console.debug('[MF885]['+(id||'TTL39-NOT-STARTED')+'] '+kind,values||{})}
  function condition(id,name,expected,observed,passed){log(id,'condition '+name,{id:name,expected:expected,observed:observed,passed:passed})}
  function valueInfo(value){value=String(value===null||value===undefined?'':value);var off=value==='off',canonical=/^[1-9][0-9]{0,2}$/.test(value),numeric=canonical?Number(value):null,inRange=canonical&&numeric>=1&&numeric<=255;return {raw:value,off:off,canonical:canonical,numeric:numeric,inRange:inRange,accepted:off||inRange}}
  function label(value){var parsed=valueInfo(value);return parsed.off?'Off':!parsed.accepted?'Unknown':value==='64'?'64 · Recommended':value==='65'?'65 · Compatibility':'TTL '+value}
  function elements(parent){var result=[],items=parent&&parent.childNodes?parent.childNodes:[];for(var i=0;i<items.length;i++)if(items[i].nodeType===1)result.push(items[i]);return result}
  function quiet(value){return !String(value||'').trim()}
  function strictState(doc){
    var id=doc&&doc.mfRequestId||serial(),root=doc&&doc.documentElement,rootChildren=elements(root),model=rootChildren.length===1&&String(rootChildren[0].nodeName||'').toLowerCase()==='diagnostic'?rootChildren[0]:null,fields=elements(model),names=fields.map(function(item){return String(item.nodeName||'').toLowerCase()}),values=fields.map(function(item){return String(item.textContent||'').trim()}),attrsRoot=root&&root.attributes?root.attributes.length:null,attrsModel=model&&model.attributes?model.attributes.length:null,fieldAttrs=fields.reduce(function(total,item){return total+(item.attributes?item.attributes.length:0)},0),fieldChildren=fields.reduce(function(total,item){return total+elements(item).length},0),shape=!!root&&String(root.nodeName||'').toUpperCase()==='RGW'&&attrsRoot===0&&rootChildren.length===1&&!!model&&attrsModel===0&&fields.length===3&&names.join(',')==='command,arg,output'&&fieldAttrs===0&&fieldChildren===0&&quiet(root.textContent.replace(model.textContent,''))&&quiet(root.tail)&&quiet(model.tail)&&fields.every(function(item){return quiet(item.tail)}),command=values[0]||'',arg=values[1]||'',output=values[2]||'',parsed=valueInfo(arg),empty=shape&&command===''&&arg===''&&output==='',retained=shape&&command==='ttl'&&parsed.accepted&&output==='',accepted=empty||retained;
    var variables={rootTag:root&&String(root.nodeName||''),rootAttributeCount:attrsRoot,rootChildCount:rootChildren.length,diagnosticPresent:!!model,diagnosticAttributeCount:attrsModel,fieldCount:fields.length,fieldOrder:names,fieldAttributeCount:fieldAttrs,fieldChildElementCount:fieldChildren,command:command,arg:arg,output:output,argOff:parsed.off,argCanonicalDecimal:parsed.canonical,argNumeric:parsed.numeric,argInRange:parsed.inRange,argAccepted:parsed.accepted,stockEmpty:empty,retainedRequest:retained,accepted:accepted,packetPathInferred:false,retryCeiling:0};
    log(id,'readback variables',variables);
    condition(id,'root_tag','RGW',variables.rootTag,variables.rootTag==='RGW');
    condition(id,'root_attribute_count',0,attrsRoot,attrsRoot===0);
    condition(id,'root_child_count',1,rootChildren.length,rootChildren.length===1);
    condition(id,'diagnostic_model_present',true,!!model,!!model);
    condition(id,'diagnostic_attribute_count',0,attrsModel,attrsModel===0);
    condition(id,'field_count',3,fields.length,fields.length===3);
    condition(id,'field_order','command,arg,output',names.join(','),names.join(',')==='command,arg,output');
    condition(id,'field_attribute_count',0,fieldAttrs,fieldAttrs===0);
    condition(id,'field_child_element_count',0,fieldChildren,fieldChildren===0);
    condition(id,'output_empty',true,output==='',output==='');
    condition(id,'state_is_stock_empty_or_retained_ttl',true,accepted,accepted);
    if(!accepted)throw core.ttlBridge.fault('E_TTL_RESPONSE','The router returned an ambiguous TTL request state.',id,variables);
    return {requestId:id,kind:empty?'boot-default':'retained',value:empty?'off':arg,variables:variables};
  }
  function syncControls(){
    var busy=!core||core.ttlBridge.routerBusy(),enabled=!!core&&core.ttlBridge.sessionPresent()&&!busy&&!runtime.locked&&runtime.current!==null,refresh=node('ttlRefresh');
    if(refresh)refresh.disabled=!core||!core.ttlBridge.sessionPresent()||busy;
    var buttons=w.document.querySelectorAll('button[data-ttl-value]');for(var i=0;i<buttons.length;i++)buttons[i].disabled=!enabled;
    if(node('ttlCustom'))node('ttlCustom').disabled=!enabled;if(node('ttlCustomApply'))node('ttlCustomApply').disabled=!enabled;
  }
  function render(state){
    runtime.current=state.value;runtime.kind=state.kind;node('ttlRequested').textContent=label(state.value);node('ttlRequestedDetail').textContent=state.kind==='boot-default'?'No TTL request is retained; the native boot default is Off.':'The router retained this requested value. Packet application is checked separately.';
    var card=state.value==='off'||state.value==='64'||state.value==='65'?state.value:'custom',cards=w.document.querySelectorAll('[data-ttl-card]');for(var i=0;i<cards.length;i++){var active=cards[i].getAttribute('data-ttl-card')===card;cards[i].classList.toggle('active',active);cards[i].setAttribute('aria-current',active?'true':'false')}if(card==='custom')node('ttlCustom').value=state.value;syncControls();
  }
  function read(trigger){
    if(!core||!core.ttlBridge.sessionPresent())return Promise.resolve(null);var id=serial(),manual=String(trigger||'').indexOf('manual')===0,owner='ttl-read';log(id,'read variables',{trigger:trigger||'manual',manual:manual,method:'GET',model:'diagnostic',getCeiling:1,postCeiling:0,tcpConnectCeiling:1,retryCeiling:0,lockedBefore:runtime.locked});
    if(!core.ttlBridge.begin(owner,'ttlStatus'))return Promise.resolve(null);core.ttlBridge.status('ttlStatus','Reading the last TTL request…');
    return core.ttlBridge.get(owner).then(function(doc){var state=strictState(doc),wasLocked=runtime.locked;if(!runtime.locked||manual)runtime.locked=false;runtime.nextAt=Date.now()+READ_INTERVAL_MS;render(state);core.ttlBridge.status('ttlStatus',(state.kind==='boot-default'?'No TTL request is retained; the image initializes its private state to Off.':'Last requested value '+label(state.value)+'.')+(wasLocked&&!manual?' Read succeeded, but writes remain locked until a manual read.':'')+' Packet application and restart behavior are checked separately · '+state.requestId+'.');log(id,'terminal',{terminalReason:wasLocked&&!manual?'TTL_REQUEST_STATE_PROVEN_WRITE_LOCK_RETAINED':'TTL_REQUEST_STATE_PROVEN',stateKind:state.kind,requestedValue:state.value,writeLockRetained:wasLocked&&!manual,packetPathInferred:false,getCount:1,postCount:0,retryCount:0});return state}).catch(function(error){runtime.locked=true;runtime.nextAt=Date.now()+READ_INTERVAL_MS;syncControls();core.ttlBridge.showError('ttlStatus',error,'TTL read failed.',' Writes are locked; no retry was sent.');log(id,'terminal',{terminalReason:'TTL_READ_FAILED',reasonCode:error&&error.mfCode||'E_CLIENT',getCount:1,postCount:0,retryCount:0});throw error}).finally(function(){core.ttlBridge.end(owner)});
  }
  function requestBody(value){return core.ttlBridge.xmlDeclaration+'<RGW><diagnostic><command>ttl</command><arg>'+value+'</arg></diagnostic></RGW>'}
  function strictPostEnvelope(reply,id,requested){var doc=core.parseXml(reply.body,reply.requestId),root=doc.documentElement,children=elements(root),attrsRoot=root&&root.attributes?root.attributes.length:null,rootOnly=!!root&&String(root.nodeName||'').toUpperCase()==='RGW'&&attrsRoot===0&&children.length===0&&quiet(root.textContent)&&quiet(root.tail),model=children.length===1&&String(children[0].nodeName||'').toLowerCase()==='diagnostic'?children[0]:null,fields=elements(model),names=fields.map(function(item){return String(item.nodeName||'').toLowerCase()}),fieldAttrs=fields.reduce(function(total,item){return total+(item.attributes?item.attributes.length:0)},0),fieldChildren=fields.reduce(function(total,item){return total+elements(item).length},0),values=fields.map(function(item){return String(item.textContent||'').trim()}),echo=!!root&&String(root.nodeName||'').toUpperCase()==='RGW'&&attrsRoot===0&&children.length===1&&!!model&&model.attributes.length===0&&fields.length===3&&names.join(',')==='command,arg,output'&&fieldAttrs===0&&fieldChildren===0&&values[0]==='ttl'&&values[1]===requested&&values[2]===''&&quiet(root.textContent.replace(model.textContent,''))&&quiet(root.tail)&&quiet(model.tail)&&fields.every(function(item){return quiet(item.tail)}),passed=reply.status===200&&(rootOnly||echo),variables={status:reply.status,rootTag:root&&String(root.nodeName||''),rootAttributeCount:attrsRoot,rootChildCount:children.length,diagnosticPresent:!!model,fieldCount:fields.length,fieldOrder:names,fieldAttributeCount:fieldAttrs,fieldChildElementCount:fieldChildren,echoCommand:values[0]||'',echoArg:values[1]||'',echoOutput:values[2]||'',requestedValue:requested,rootOnlyEnvelope:rootOnly,matchingEchoEnvelope:echo,acceptedTransportEnvelope:passed,responseIsStateProof:false};log(id,'post response variables',variables);condition(id,'post_status',200,reply.status,reply.status===200);condition(id,'post_envelope_root_only_or_matching_echo',true,rootOnly||echo,rootOnly||echo);condition(id,'post_response_is_state_proof',false,false,true);if(!passed)throw core.ttlBridge.fault('E_TTL_SET_RESPONSE','The TTL request response envelope changed.',reply.requestId,variables);return true}
  function setValue(value){
    value=String(value===null||value===undefined?'':value);var id=serial(),parsed=valueInfo(value),known=runtime.current!==null,unlocked=!runtime.locked,different=value!==runtime.current,body=parsed.accepted?requestBody(value):'';log(id,'set variables',{requested:value,requestedOff:parsed.off,requestedCanonicalDecimal:parsed.canonical,requestedNumeric:parsed.numeric,requestedInRange:parsed.inRange,requestedAccepted:parsed.accepted,currentRequestedValue:runtime.current,currentStateKind:runtime.kind,currentKnown:known,mutationUnlocked:unlocked,different:different,requestBody:body,requestBodyCharacters:body.length,outputFieldPresent:false,postCeiling:1,readbackGetCeiling:1,totalRequestCeiling:2,retryCeiling:0});
    condition(id,'requested_value_canonical',true,parsed.off||parsed.canonical,parsed.off||parsed.canonical);condition(id,'requested_value_in_range_or_off',true,parsed.accepted,parsed.accepted);condition(id,'request_body_has_no_output',false,body.indexOf('<output')>=0,body.indexOf('<output')<0);condition(id,'mutation_unlocked',true,unlocked,unlocked);condition(id,'current_request_state_known',true,known,known);condition(id,'requested_value_differs',true,different,different);
    if(!parsed.accepted){core.ttlBridge.showError('ttlStatus',core.ttlBridge.fault('E_TTL_VALUE','TTL must be Off or a canonical integer from 1 to 255.',id),'TTL was not requested.');return}
    if(!unlocked||!known){core.ttlBridge.showError('ttlStatus',core.ttlBridge.fault(!unlocked?'E_TTL_LOCKED':'E_TTL_STATE_UNKNOWN',!unlocked?'A previous TTL outcome is ambiguous. Read the last request manually first.':'Read the current TTL request state first.',id),'TTL was not requested.');return}
    if(!different){core.ttlBridge.status('ttlStatus','Last requested value is already '+label(value)+'. No request was sent.');log(id,'terminal',{terminalReason:'TTL_REQUEST_ALREADY_RETAINED',getCount:0,postCount:0,retryCount:0});return}
    if(value!=='off'&&!w.confirm('Request TTL '+value+'? A separate readback proves request retention; packet application and restart behavior are verified separately.')){log(id,'terminal',{terminalReason:'TTL_OPERATOR_CANCELLED',getCount:0,postCount:0,retryCount:0});return}
    var owner='ttl-set',submitted=false,getCount=0,postCount=0;if(!core.ttlBridge.begin(owner,'ttlStatus'))return;core.ttlBridge.status('ttlStatus','Sending one TTL request, then one separate readback…');
    submitted=true;postCount=1;log(id,'post intent',{bodyFullyPrepared:true,requestBody:body,requestBodyCharacters:body.length,postCountIntent:1});core.ttlBridge.post(body,owner).then(function(reply){strictPostEnvelope(reply,id,value);getCount=1;return core.ttlBridge.get(owner)}).then(function(doc){var state=strictState(doc),matches=state.kind==='retained'&&state.value===value;condition(id,'readback_kind','retained',state.kind,state.kind==='retained');condition(id,'readback_matches_request',value,state.value,matches);if(!matches)throw core.ttlBridge.fault('E_TTL_READBACK','The retained TTL request does not match the submitted value.',state.requestId,{requested:value,observed:state.value,stateKind:state.kind});runtime.locked=false;runtime.nextAt=Date.now()+READ_INTERVAL_MS;render(state);core.ttlBridge.status('ttlStatus','Requested '+label(value)+' and proved matching retention. Packet application and restart behavior are checked separately; no retry was sent.');log(id,'terminal',{terminalReason:'TTL_REQUEST_RETAINED',requestedValue:value,packetPathInferred:false,getCount:getCount,postCount:postCount,retryCount:0})}).catch(function(error){if(submitted)runtime.locked=true;syncControls();core.ttlBridge.showError('ttlStatus',error,submitted?'TTL request outcome is ambiguous.':'TTL was not requested.',submitted?' Writes are locked; no retry was sent.':'');log(id,'terminal',{terminalReason:submitted?'TTL_REQUEST_OUTCOME_AMBIGUOUS':'TTL_REQUEST_NOT_SENT',reasonCode:error&&error.mfCode||'E_CLIENT',getCount:getCount,postCount:postCount,retryCount:0})}).finally(function(){core.ttlBridge.end(owner)});
  }
  function authenticated(trigger){runtime.nextAt=0;return read(trigger||'bootstrap')}
  function logout(){runtime.current=null;runtime.kind=null;runtime.locked=false;runtime.nextAt=0;if(node('ttlRequested'))node('ttlRequested').textContent='Not loaded';if(node('ttlRequestedDetail'))node('ttlRequestedDetail').textContent='No diagnostic read has completed.';if(node('ttlStatus'))core.ttlBridge.status('ttlStatus','TTL data will load with the rest of the interface after sign-in.');syncControls()}
  function dueAt(now){return runtime.nextAt||Number(now)||Date.now()}
  function due(now){return !!core&&core.ttlBridge.sessionPresent()&&(!runtime.nextAt||Number(now)>=runtime.nextAt)}
  function resetDue(){runtime.nextAt=0}
  function bind(){if(runtime.bound)return;runtime.bound=true;node('ttlRefresh').addEventListener('click',function(){read('manual-ttl').catch(function(){return null})});var buttons=w.document.querySelectorAll('button[data-ttl-value]');for(var i=0;i<buttons.length;i++)buttons[i].addEventListener('click',function(){setValue(this.getAttribute('data-ttl-value'))});node('ttlCustomApply').addEventListener('click',function(){setValue(node('ttlCustom').value)});syncControls()}
  w.MF885CommunityR39TTL={version:'0.3.9-community-r2',runtime:runtime,valueInfo:valueInfo,strictState:strictState,requestBody:requestBody,read:read,setValue:setValue,authenticated:authenticated,logout:logout,dueAt:dueAt,due:due,resetDue:resetDue,syncControls:syncControls,bind:bind};
  if(w.document.readyState==='loading')w.document.addEventListener('DOMContentLoaded',bind);else bind();
})(window);
