  function wanRows(snapshot){
    var fields=[['WAN IPv4',['ipv4','ip','ip_address','wan_ip','IP_address']],['WAN IPv6',['ipv6','ipv6_address','wan_ipv6','IPv6_address']],['Gateway',['gateway','v4gateway','ipv4_gateway','wan_gateway']],['Primary DNS',['dns1','v4dns1','primary_dns']],['Secondary DNS',['dns2','v4dns2','secondary_dns']],['Configured APN',['apn','configured_apn','lte_apn']],['Active APN',['active_apn','current_apn','used_apn','wan_apn']],['Subnet mask',['mask']],['MTU',['mtu']],['WAN link state · raw',['wan_link_status']],['WAN connection state · raw',['wan_conn_status']],['PDP type · raw',['pdp_type']],['Connection state · raw',['connect_disconnect']],['Connection mode · raw',['connect_mode']],['Radio preference · raw',['prefer_mode']]];
    var rows=fields.map(function(field){var candidates=[];['wan','status1'].forEach(function(model){field[1].forEach(function(key){candidates.push([model,['wan',key]]);candidates.push([model,['wan','cellular',key]])})});return row(field[0],directValue(picked(snapshot,candidates)))});
    var entry=snapshot.endpoints.status1,doc=entry&&entry.ok?entry.doc:null;
    var roots=doc?children(doc.documentElement,'wan'):[],cells=roots.length===1?children(roots[0],'cellular'):[],lists=cells.length===1?children(cells[0],'pdp_context_list'):[],items=lists.length===1?children(lists[0],'Item'):[];
    items.slice(0,16).forEach(function(item,index){[['apn','APN'],['ipv4','IPv4'],['ipv6','IPv6'],['v4gateway','Gateway'],['v4dns1','Primary DNS'],['v4dns2','Secondary DNS']].forEach(function(field){var value=one(item,field[0]);if(value!==null&&value!=='')rows.push(['PDP '+(index+1)+' · '+field[1],value,'Source: status1 · wan/cellular/pdp_context_list/Item['+(index+1)+']/'+field[0]])})});
    return rows;
  }
  function renderWan(snapshot){var rows=wanRows(snapshot),available=rows.filter(function(r){return r[1]!=='Not returned'}),missing=rows.filter(function(r){return r[1]==='Not returned'});renderValues('wanValues',available.length?available:[['WAN','Not returned']]);renderValues('wanMissingValues',missing);node('wanMissing').hidden=missing.length===0;}
