(function(){
  if(window.MF885_COMMUNITY_CANARY)return;
  var marker='MF885 Community Canary Logs 0.0-logs-r2',events=[],sequence=0,requestSequence=0,paused=false,pollBusy=false,dropped=0,eventUnits=0,maxEvents=240,maxUnits=96000,lastDetailed='';
  window.MF885_COMMUNITY_CANARY={id:'0.0-logs-r2',kind:'webui-logs',marker:marker,schema:2};
  var css='#zmiDbgToggle{position:fixed;right:10px;bottom:10px;z-index:2147483646;padding:7px 10px;background:#17384d;color:#fff}#zmiDbgPanel{display:none;position:fixed;z-index:2147483647;inset:8px;background:#f5f7f8;color:#1b2730;border:1px solid #607d8b;font:12px Arial}#zmiDbgPanel.open{display:flex;flex-direction:column}#zmiDbgPanel header{display:flex;gap:6px;padding:8px;background:#24485e;color:#fff}#zmiDbgPanel header b{margin-right:auto}#zmiDbgPanel button,#zmiDbgPanel input,#zmiDbgPanel select{padding:4px;border:1px solid #78909c}#zmiDbgMeta{padding:5px 8px}#zmiDbgList{flex:1;overflow:auto;padding:5px;background:#fff}#zmiDbgList article{margin:0 0 5px;padding:5px;border-left:3px solid #607d8b;background:#f1f4f5}#zmiDbgList article.err{border-color:#c62828}#zmiDbgList article.net{border-color:#0277bd}#zmiDbgList time{color:#607d8b}#zmiDbgList pre{white-space:pre-wrap;word-break:break-all;max-height:180px;overflow:auto}';
  var style=document.createElement('style');style.id='zmiCanaryLogsStyle';style.appendChild(document.createTextNode(css));(document.head||document.getElementsByTagName('head')[0]).appendChild(style);
  var toggle=document.createElement('button');toggle.type='button';toggle.id='zmiDbgToggle';toggle.title='Logs';toggle.innerHTML='Logs <span id="zmiDbgBadge">0</span>';
  var panel=document.createElement('section');panel.id='zmiDbgPanel';panel.setAttribute('aria-label','MF885 live technical logs');panel.innerHTML='<header><b>MF885 Canary Logs r2</b><input id="zmiDbgFilter" placeholder="filter"><select id="zmiDbgKind"><option value="">all</option><option>network</option><option>error</option><option>ui</option><option>console</option><option>lifecycle</option></select><button id="zmiDbgPause">Pause</button><button id="zmiDbgClear">Clear</button><button id="zmiDbgCopy">Copy</button><button id="zmiDbgClose">Close</button></header><div id="zmiDbgMeta">Schema 2 · SMS/credentials hidden</div><div id="zmiDbgList"></div>';
  document.body.appendChild(toggle);document.body.appendChild(panel);
  function now(){try{return new Date().toISOString()}catch(e){return String(new Date())}}
  function text(value){if(value===undefined||value===null)return'';if(typeof value==='string')return value;try{if(window.XMLSerializer&&value&&value.nodeType)return new XMLSerializer().serializeToString(value)}catch(e){}try{return JSON.stringify(value)}catch(e){return String(value)}}
  function isSms(url,body){return /(?:[?&]file=message(?:[&#\s]|$)|<(?:message|get_message|send_message|delete_message|message_content|sms_content|sms_message)\b)/i.test(String(url||'')+' '+String(body||''))}
  function safe(value,sms){var out=text(value),k='pass(?:word|wd)?|pwd|pin|puk|psk|wifi[-_]?(?:key|password)|token|(?:access|refresh)[-_]?token|(?:x[-_]?)?api[-_]?key|secret|client[-_]?secret|jwt|bearer|session[-_]?id|sid|nonce|cnonce|response|(?:proxy[-_]?)?auth(?:orization)?|(?:set[-_]?)?cookie|imei|imsi|iccid|serial(?:[-_]?number)?|device[-_]?(?:sn|serial)|sn|(?:current[-_]?)?device[-_]?mac|(?:wifi|lan|client)[-_]?mac|wifimac|ssid|apn|pdp[-_]?name|ip[-_]?(?:address|addr)|ipv6[-_]?addr|phone(?:[-_]?number)?|username|msisdn';if(sms&&out)return'<SMS hidden>';out=out.replace(/\b(?:Authorization|Proxy-Authorization|Cookie|Set-Cookie)\b\s*:\s*[^\r\n]*/gi,'<header hidden>');out=out.replace(new RegExp('<('+k+')\\b[^>]*?(?:\\/\\s*>|>[\\s\\S]*?<\\/\\1>)','gi'),'<$1><hidden></$1>');out=out.replace(new RegExp('(["\\\']?\\b(?:'+k+')["\\\']?\\s*[:=]\\s*)(?:"(?:\\\\.|[^"\\\\])*"|\\\'(?:\\\\.|[^\\\'\\\\])*\\\'|[^\\s,;&}]+)','gi'),'$1<hidden>');out=out.replace(/([?&](?:token|access[-_]?token|(?:x[-_]?)?api[-_]?key|session[-_]?id|pass(?:word|wd)?|pwd|nonce|cnonce|response)=)[^&#]*/gi,'$1<hidden>');out=out.replace(/\b[0-9a-f]{1,4}(?:(?::[0-9a-f]{0,4}){3,7}|(?::[0-9a-f]{1,4})*::[\da-f:.]*)(?=\W|$)|::[\da-f:.]*(?=\W|$)|\b(?:\d{1,3}\.){3}\d{1,3}\b|\b\d{14,20}\b|\+\d[\d ()-]{6,}\d/gi,'<hidden>');return out}
  function endpoint(url){var value=String(url||''),match=value.match(/[?&]file=([^&#]+)/i);try{return match?decodeURIComponent(match[1]):value.replace(/^https?:\/\/[^/]+/i,'').slice(0,180)}catch(e){return value.slice(0,180)}}
  function hash(value){var h=5381,s=String(value||'');for(var i=0;i<s.length;i++)h=((h<<5)+h)^s.charCodeAt(i);return(h>>>0).toString(16)}
  function badge(){var badge=document.getElementById('zmiDbgBadge'),meta=document.getElementById('zmiDbgMeta');if(badge)badge.textContent=String(events.length);if(meta)meta.textContent='Schema 2 · '+events.length+' events · '+eventUnits+' units · dropped '+dropped+' · SMS/credentials hidden'}
  function add(kind,phase,title,detail,rid){var item={id:++sequence,at:now(),kind:String(kind||'event'),phase:String(phase||'event'),requestId:rid||null,title:safe(title,false).slice(0,300),detail:safe(detail,false).slice(0,12000)},size;try{size=JSON.stringify(item).length}catch(e){size=300}item.size=size;events.push(item);eventUnits+=size;while(events.length>maxEvents||eventUnits>maxUnits){var old=events.shift();eventUnits-=old.size||0;dropped++}badge();if(!paused)render()}
  function render(){var root=document.getElementById('zmiDbgList'),filter=document.getElementById('zmiDbgFilter'),kind=document.getElementById('zmiDbgKind');if(!root)return;var q=filter?String(filter.value||'').toLowerCase():'',selected=kind?kind.value:'',fragment=document.createDocumentFragment();root.innerHTML='';for(var i=events.length-1;i>=0;i--){var item=events[i],hay=(item.kind+' '+item.phase+' '+item.title+' '+item.detail).toLowerCase();if(selected&&item.kind!==selected||q&&hay.indexOf(q)<0)continue;var row=document.createElement('article');row.className=item.kind==='error'?'err':item.kind==='network'?'net':'';var head=document.createElement('div'),time=document.createElement('time'),strong=document.createElement('strong');time.appendChild(document.createTextNode(item.at+' #'+item.id+(item.requestId?' req '+item.requestId:'')));strong.appendChild(document.createTextNode(item.kind+' · '+item.phase+' · '+item.title));head.appendChild(time);head.appendChild(strong);row.appendChild(head);if(item.detail){var pre=document.createElement('pre');pre.appendChild(document.createTextNode(item.detail));row.appendChild(pre)}fragment.appendChild(row)}root.appendChild(fragment)}
  function report(){var out=[marker,'schema=2','generated='+now(),'events='+events.length,'units='+eventUnits,'dropped='+dropped,'sms_bodies=hidden','credentials=redacted',''];for(var i=0;i<events.length;i++){var e=events[i];out.push(e.at+' #'+e.id+(e.requestId?' req '+e.requestId:'')+' '+e.kind+' '+e.phase+' '+e.title);if(e.detail)out.push(e.detail);out.push('')}return out.join('\n')}
  function copied(){var button=document.getElementById('zmiDbgCopy');if(button){button.textContent='Copied';setTimeout(function(){button.textContent='Copy'},1200)}}
  function legacyCopy(value){var area=document.createElement('textarea');area.value=value;area.style.position='fixed';area.style.left='-9999px';document.body.appendChild(area);area.select();try{document.execCommand('copy')}catch(e){}document.body.removeChild(area);copied()}
  function copy(){var value=report();if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(value).then(copied,function(){legacyCopy(value)});return}legacyCopy(value)}
  function openPanel(){panel.className='open';render();pollDetailedLog()}
  function closePanel(){panel.className=''}
  var xhrOpen=XMLHttpRequest.prototype.open,xhrSend=XMLHttpRequest.prototype.send;
  XMLHttpRequest.prototype.open=function(method,url){this.__zmiLog={id:++requestSequence,method:String(method||'GET').toUpperCase(),url:String(url||''),started:0,failure:''};return xhrOpen.apply(this,arguments)};
  XMLHttpRequest.prototype.send=function(body){var self=this,meta=this.__zmiLog||{id:++requestSequence,method:'?',url:'',failure:''},generation=this.__zmiGeneration=(this.__zmiGeneration||0)+1,bodyText=text(body),sms=isSms(meta.url,bodyText);meta.started=Date.now();add('network','start',meta.method+' '+endpoint(meta.url),'request_bytes='+bodyText.length+(bodyText?'\nrequest_body='+safe(bodyText,sms):''),meta.id);function current(){return self.__zmiGeneration===generation}function fail(name){if(current())meta.failure=name}function done(){if(!current())return;var response='';try{response=self.responseText||''}catch(e){response='<response unreadable>'}var phase=meta.failure||'end',detail='status='+String(self.status||0)+' duration_ms='+(Date.now()-meta.started)+' bytes='+response.length;if(response)detail+='\nresponse_body='+safe(response,isSms(meta.url,response));if(endpoint(meta.url)==='detailed_log'){var sig=hash(response),items=(response.match(/<Item\b/gi)||[]).length;detail+='\ndetailed_log_items='+items+' changed='+(lastDetailed!==sig);lastDetailed=sig}add(meta.failure||self.status>=400?'error':'network',phase,meta.method+' '+endpoint(meta.url),detail,meta.id)}try{for(var i=0,n=['error','abort','timeout'];i<n.length;i++)(function(name){self.addEventListener(name,function(){fail(name)},false)})(n[i]);self.addEventListener('loadend',done,false);return xhrSend.apply(this,arguments)}catch(e){add('error','send',meta.method+' '+endpoint(meta.url),'send failed: '+safe(e&&e.message||e,false),meta.id);throw e}};
  if(window.fetch){var nativeFetch=window.fetch;window.fetch=function(input,init){var url=typeof input==='string'?input:input&&input.url||'',method=String(init&&init.method||'GET').toUpperCase(),body=init&&init.body||'',sms=isSms(url,body),started=Date.now(),id=++requestSequence;add('network','start',method+' '+endpoint(url),'request_bytes='+text(body).length+(body?'\nrequest_body='+safe(body,sms):''),id);return nativeFetch.apply(this,arguments).then(function(response){try{response.clone().text().then(function(value){add(response.status>=400?'error':'network','end',method+' '+endpoint(url),'status='+response.status+' duration_ms='+(Date.now()-started)+' bytes='+value.length+(value?'\nresponse_body='+safe(value,isSms(url,value)):''),id)})}catch(e){}return response},function(error){add('error','exception',method+' '+endpoint(url),'failed after '+(Date.now()-started)+' ms: '+safe(error&&error.message||error,false),id);throw error})}};
  document.addEventListener('submit',function(event){var form=event.target,names=[],elements=form&&form.elements||[];for(var i=0;i<elements.length;i++)if(elements[i].name||elements[i].id)names.push(elements[i].name||elements[i].id);add('ui','submit',String(form.method||'GET').toUpperCase()+' '+endpoint(form.action||location.pathname),'fields='+names.join(','))},true);
  document.addEventListener('click',function(event){var node=event.target;while(node&&node!==document&&!/^(A|BUTTON|INPUT)$/.test(node.tagName||''))node=node.parentNode;if(node&&node!==document)add('ui','click','control',String(node.id||node.name||node.tagName).slice(0,220))},true);
  if(window.console){for(var ci=0,names=['error','warn','log','info'];ci<names.length;ci++)(function(name){var original=window.console[name];if(typeof original!=='function')return;window.console[name]=function(){try{var value=Array.prototype.join.call(arguments,' ');add(name==='error'?'error':'console',name,'console.'+name,safe(value,isSms('',value)))}catch(e){}return original.apply(window.console,arguments)}})(names[ci])}
  window.addEventListener('error',function(event){add('error','javascript','window error',String(event.message||'error')+' @ '+String(event.filename||'')+':'+String(event.lineno||0))});
  window.addEventListener('unhandledrejection',function(event){add('error','promise','unhandled rejection',safe(event.reason&&event.reason.message||event.reason||'unknown',false))});
  window.addEventListener('online',function(){add('lifecycle','online','network','browser online')});window.addEventListener('offline',function(){add('lifecycle','offline','network','browser offline')});document.addEventListener('visibilitychange',function(){add('lifecycle','visibility','document',String(document.visibilityState||'unknown'))});
  function pollDetailedLog(){if(panel.className!=='open'||pollBusy)return;pollBusy=true;var request=new XMLHttpRequest();try{request.open('GET','xml_action.cgi?method=get&module=duster&file=detailed_log',true);request.setRequestHeader('Authorization',getAuthHeader('GET'));request.onreadystatechange=function(){if(request.readyState===4)pollBusy=false};request.onerror=function(){pollBusy=false};request.send(null)}catch(e){pollBusy=false;add('error','poll','detailed_log',e&&e.message||e)}}
  toggle.onclick=openPanel;document.getElementById('zmiDbgClose').onclick=closePanel;document.getElementById('zmiDbgPause').onclick=function(){paused=!paused;this.textContent=paused?'Resume':'Pause';if(!paused)render()};document.getElementById('zmiDbgClear').onclick=function(){events=[];eventUnits=0;badge();render()};document.getElementById('zmiDbgCopy').onclick=copy;document.getElementById('zmiDbgFilter').oninput=render;document.getElementById('zmiDbgKind').onchange=render;
  setInterval(pollDetailedLog,8000);add('lifecycle','loaded','canary',marker+' · '+location.href);
})();
