/* MF885 Community 0.4.7-dev.18 - base 2.5.94 */
(function(w){
  'use strict';
  var VERSION='0.4.7-dev.18',REQUEST_TIMEOUT_MS=10000,SNAPSHOT_POLL_MS=30000,MESSAGES_POLL_MS=60000,MAX_MESSAGE_PAGES=20,MAX_MESSAGE_ID_PARTS=64,MAX_MESSAGE_ID_CHARACTERS=8192,DISPLAY_PAGE_SIZE=10,STATUS_POLLS=10,MAX_SMS_UNITS=268;
  var XML_DECLARATION='<?xml version="1.0" encoding="US-ASCII"?> ';
  var ENDPOINTS=['status1','wan','Engineer_parameter'];
  var FOLDERS={inbox:{flag:'GET_RCV_SMS_LOCAL',label:'Device inbox',tags:'12',store:'1',deletable:true},sent:{flag:'GET_SENT_SMS_LOCAL',label:'Sent messages',tags:'2',store:'1'},sim:{flag:'GET_SIM_SMS',label:'SIM messages',tags:'',store:'0'},drafts:{flag:'GET_DRAFT_SMS',label:'Drafts',tags:'2',store:'2'}};
  var session=null,requestEpoch=1,expiryHandled=0,operationToken=0,currentRequest=null,routerOwner=null,cpuTracker=null,cpuSnapshot=null,cpuReadState=null,messages=[],messagePage=1,messagesComplete=false,messagesMutationSafe=false,messagesBusy=false,messagesCancelError=null,mutationBusy=false,mutationLocked=false,requestSequence=0,errorSequence=0,snapshotSequence=0,liveSequence=0,diagnosticsSnapshot=null,snapshotBusy=false,activePage='dashboard',liveEnabled=true,liveTimer=null,nextSnapshotAt=0,nextMessagesAt=0,bootstrapBusy=false,lastMessagesAt=null;

  function node(id){return w.document.getElementById(id)}
  function status(id,text,error){var target=node(id);target.textContent=text;target.className='status'+(error?' error':'')}
  function serial(prefix,value){return prefix+'-'+('0000'+value).slice(-4)}
  function nextRequestId(){requestSequence++;return serial('R46',requestSequence)}
  function nextErrorId(){errorSequence++;return serial('ERR46',errorSequence)}
  function nextUnexpectedId(){errorSequence++;return serial('JS42',errorSequence)}
  function nextSnapshotId(){snapshotSequence++;return serial('S42',snapshotSequence)}
  function nextLiveId(){liveSequence++;return serial('LIVE42',liveSequence)}
  function liveLog(id,kind,values){if(w.console&&typeof w.console.debug==='function')privateLog('debug','[MF885]['+(id||'LIVE42-NOT-STARTED')+'] '+kind,values||{})}
  function liveCondition(id,name,expected,observed,passed){liveLog(id,'condition '+name,{id:name,expected:expected,observed:observed,passed:passed})}
  function safeRoute(url){return String(url||'').split('?')[0]||'/'}
  function fault(code,message,id,meta){var error=new Error(message);error.mfCode=code;if(id)error.mfId=id;if(meta)error.mfMeta=meta;return error}
  function attachFault(error,code,id,meta){var value=error&&typeof error==='object'?error:new Error(String(error||'Interface error.'));if(!value.mfCode)value.mfCode=code||'E_CLIENT';if(!value.mfId&&id)value.mfId=id;if(!value.mfMeta&&meta)value.mfMeta=meta;return value}
  function normalizeError(error,fallback){var value=error&&typeof error==='object'?error:new Error(fallback||String(error||'Interface error.'));if(!value.message)value.message=fallback||'Interface error.';if(!value.mfCode)value.mfCode='E_CLIENT';if(!value.mfId)value.mfId=nextErrorId();return value}
  function errorText(error,fallback){var value=normalizeError(error,fallback);return (value.message||fallback||'Interface error.')+' ['+value.mfCode+' · '+value.mfId+']'}
  function logFailure(error,fallback){var value=normalizeError(error,fallback);if(value.mfLogged)return value;value.mfLogged=true;if(w.console&&typeof w.console.error==='function')privateLog('error','[MF885]['+value.mfId+']['+value.mfCode+'] '+value.message,value.mfMeta||{},value);return value}
  function showError(id,error,fallback,suffix){var value=logFailure(error,fallback);status(id,errorText(value,fallback)+(suffix||''),true);return value}
  function reportUnexpected(kind,reason){var id=nextUnexpectedId(),target=node('runtimeStatus'),message='Unexpected interface error. [E_UNEXPECTED · '+id+'] Details are in the browser console.';if(target){target.textContent=message;target.hidden=false}if(w.console&&typeof w.console.error==='function')privateLog('error','[MF885]['+id+'][E_UNEXPECTED] '+String(kind||'error'),reason);return id}
  function syncRouterControls(){var busy=routerOwner!==null,messageBlocked=busy||messagesBusy;node('refreshAll').disabled=busy;node('diagnosticsRefresh').disabled=busy;node('modemRefresh').disabled=busy;node('logout').disabled=busy;node('messagesRefresh').disabled=messageBlocked;node('messagesNew').disabled=messageBlocked||mutationLocked;node('messagesCancel').disabled=routerOwner!=='messages-read'||mutationBusy;node('folder').disabled=messageBlocked;node('messageSend').disabled=messageBlocked||mutationLocked;node('messageDiscard').disabled=messageBlocked;var deletes=w.document.querySelectorAll('button[data-delete-id]');for(var i=0;i<deletes.length;i++)deletes[i].disabled=busy||mutationBusy||mutationLocked;var ttl=ttlExtension();if(ttl)ttl.syncControls();var engineering=engineeringExtension();if(engineering)engineering.syncControls();var power=w.MF885Community047Dev18Power;if(power)power.syncControls();var ussd=w.MF885Community047Dev18Console;if(ussd)ussd.syncControls()}
  function beginRouterOperation(owner,statusId){if(routerOwner!==null){showError(statusId,fault('E_ROUTER_BUSY','Another router operation is already running.'),'Router operation blocked.');return false}routerOwner=owner;operationToken++;syncRouterControls();if(w.console&&typeof w.console.debug==='function')privateLog('debug','[MF885] router operation start',{owner:owner});return operationToken}
  function endRouterOperation(owner,token){if(routerOwner!==owner){reportUnexpected('router-operation-owner',{expected:owner,actual:routerOwner});return false}if(token!==operationToken){if(w.console&&typeof w.console.debug==='function')privateLog('debug','[MF885] stale router operation finalizer ignored',{owner:owner});return false}if(w.console&&typeof w.console.debug==='function')privateLog('debug','[MF885] router operation complete',{owner:owner});routerOwner=null;syncRouterControls();return true}
  function escapeXml(value){return String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
  function children(root,name){var result=[],wanted=String(name).toLowerCase(),items=root&&root.childNodes?root.childNodes:[];for(var i=0;i<items.length;i++)if(items[i].nodeType===1&&String(items[i].nodeName||'').toLowerCase()===wanted)result.push(items[i]);return result}
  function one(root,name){var items=children(root,name);return items.length===1?String(items[0].textContent||'').trim():null}
  function parseXml(value,requestId){var doc=new w.DOMParser().parseFromString(String(value||''),'text/xml');if(!doc.documentElement||doc.getElementsByTagName('parsererror').length||String(doc.documentElement.nodeName).toUpperCase()!=='RGW')throw fault('E_XML_INVALID','The router returned invalid XML.',requestId);var login=text(doc,'login_status');if(/^(?:KICKOFF|TIMEOUT|UNAUTHORIZED)$/i.test(login))throw fault('E_SESSION_EXPIRED','The router session expired. Sign in again.',requestId);doc.mfRequestId=requestId||'';return doc}
  function text(root,name){var list=root&&root.getElementsByTagName?root.getElementsByTagName(name):[];return list.length?String(list[0].textContent||'').trim():''}
  function exactIdentity(doc){var root=doc&&doc.documentElement;if(!root||String(root.nodeName||'').toUpperCase()!=='RGW'||doc.getElementsByTagName('login_status').length)return false;var statusRoots=children(root,'status'),sysinfo=children(root,'sysinfo');if(statusRoots.length||sysinfo.length!==1)return false;var model=one(sysinfo[0],'model_name'),hardware=one(sysinfo[0],'hardware_version'),version=one(sysinfo[0],'version_num');return /^(?:LV01|MF885)$/i.test(model||'')&&hardware==='MF96 Ver.D'&&version==='2.5.94_release_MF855_NZ_CP_2.129.003'}
  function randomHex(){var bytes=new Uint8Array(8);if(w.crypto&&w.crypto.getRandomValues)w.crypto.getRandomValues(bytes);else for(var i=0;i<bytes.length;i++)bytes[i]=Math.floor(Math.random()*256);var out='';for(var j=0;j<bytes.length;j++)out+=('0'+bytes[j].toString(16)).slice(-2);return out}
  function parseChallenge(header,requestId){var source=String(header||'').replace(/^\s*Digest\s+/i,''),result={},match,pattern=/([!#$%&'*+.^_`|~0-9A-Za-z-]+)\s*=\s*(?:"((?:\\.|[^"])*)"|([^,\s]+))/g;while((match=pattern.exec(source)))result[String(match[1]).toLowerCase()]=(match[2]!==undefined?match[2].replace(/\\(.)/g,'$1'):match[3]);var qops=String(result.qop||'').toLowerCase().split(',').map(function(value){return value.trim()});if(!result.realm||!result.nonce||qops.indexOf('auth')<0)throw fault('E_AUTH_CHALLENGE','The router returned an unsupported login challenge.',requestId);return {realm:result.realm,nonce:result.nonce,qop:'auth',opaque:result.opaque||''}}
  function proof(auth,ha1,method,uri,nc){var count=('00000000'+Number(nc).toString(16)).slice(-8),cnonce=randomHex(),response=w.hex_md5(ha1+':'+auth.nonce+':'+count+':'+cnonce+':'+auth.qop+':'+w.hex_md5(method+':'+uri));return {method:method,uri:uri,nc:count,cnonce:cnonce,response:response}}
  function digestHeader(auth,ha1,method,nc){var item=proof(auth,ha1,method,'/cgi/xml_action.cgi',nc),opaque=auth.opaque?', opaque="'+auth.opaque+'"':'';return 'Digest username="admin", realm="'+auth.realm+'", nonce="'+auth.nonce+'", uri="'+item.uri+'", response="'+item.response+'", qop='+auth.qop+', nc='+item.nc+', cnonce="'+item.cnonce+'"'+opaque}
  function nextHeader(method){if(!session)throw new Error('Sign in first.');var value=digestHeader(session.challenge,session.ha1,method,session.nc);session.nc++;return value}

  function privateLog(level,label,meta){
    if(!w.console||typeof w.console[level]!=='function')return;
    var safe={};meta=meta||{};
    ['status','elapsedMs','bodyCharacters','timeoutMs'].forEach(function(key){if(typeof meta[key]==='number'&&Number.isFinite(meta[key]))safe[key]=meta[key]});
    if(meta.method==='GET'||meta.method==='POST')safe.method=meta.method;
    safe.bodyRedacted=true;
    var event=String(label||'').indexOf('request start')>=0?'request start':String(label||'').indexOf('request complete')>=0?'request complete':String(label||'').indexOf('raw router response')>=0?'response metadata':level==='error'?'interface error':'operation metadata';
    w.console[level]('[MF885 0.4.7-dev.18] '+event,safe);
  }
  function xmlExpiry(body){if(!body||String(body).length>32768||/<!DOCTYPE|<!ENTITY/i.test(body)||!/login_status/i.test(String(body)))return false;try{var doc=new w.DOMParser().parseFromString(String(body),'text/xml');if(!doc.documentElement||doc.documentElement.nodeName!=='RGW'||doc.getElementsByTagName('parsererror').length)return false;var list=doc.getElementsByTagName('login_status');if(list.length!==1||list[0].parentNode!==doc.documentElement)return false;return /^(?:TIMEOUT|KICKOFF|UNAUTHORIZED)$/i.test(String(list[0].textContent||'').trim())}catch(error){return false}}
  function staleFault(requestId,meta){return fault('E_STALE_SESSION','A response from an earlier router session was discarded.',requestId,meta)}
  function expireSessionOnce(epoch,error,requestId,meta){if(epoch!==requestEpoch)return staleFault(requestId,meta);if(expiryHandled)return normalizeError(error);expiryHandled=1;finishLocalLogout('Your router session expired. Sign in again. Any command already submitted may have an unknown result. Nothing was retried.',true);return normalizeError(error)}
  function classifyReply(epoch,status,authorizationSent,body,requestId,meta){if(epoch!==requestEpoch)return staleFault(requestId,meta);if(authorizationSent&&status===401)return expireSessionOnce(epoch,fault('E_SESSION_EXPIRED','The router session expired. Sign in again.',requestId,meta),requestId,meta);if(xmlExpiry(body))return expireSessionOnce(epoch,fault('E_SESSION_EXPIRED','The router session expired. Sign in again.',requestId,meta),requestId,meta);return null}
  function cpuExtension(){return w.MF885Dev17Cpu||null}
  function cpuTransportOwner(owner){if(!session||routerOwner!==owner||owner!=='snapshot')throw fault('E_CPU_SESSION','The CPU read requires the shared snapshot operation lock.')}
  function cpuDocument(reply){if(!reply.body.length||reply.body.length>4096||/[^\x09\x0a\x0d\x20-\x7e]/.test(reply.body)||/<!|&/.test(reply.body)||/<\?/.test(reply.body.replace(/^\s*<\?xml\s[^?]*\?>/,'')))throw fault('E_CPU_RESPONSE','Invalid CPU response.',reply.requestId);var doc=parseXml(reply.body,reply.requestId),root=doc.documentElement;function children(n){return Array.prototype.filter.call(n.childNodes||[],function(c){return c.nodeType===1})}if(!root||root.nodeName!=='RGW'||root.attributes.length)throw fault('E_CPU_RESPONSE','Invalid CPU root.');var modules=children(root);if(modules.length!==1||modules[0].nodeName!=='diagnostic'||modules[0].attributes.length)throw fault('E_CPU_RESPONSE','Invalid CPU module.');var fields=children(modules[0]),values={};if(fields.length!==2)throw fault('E_CPU_RESPONSE','Invalid CPU fields.');fields.forEach(function(field){if(!/^(console_v1|cpu_v1)$/.test(field.nodeName)||values[field.nodeName]!==undefined||field.attributes.length||Array.prototype.some.call(field.childNodes,function(n){return n.nodeType!==3}))throw fault('E_CPU_RESPONSE','Invalid CPU field.');values[field.nodeName]=field.textContent});return values.cpu_v1}
  function cpuTrackerInstance(){var codec=cpuExtension();if(!codec)return null;if(!cpuTracker)cpuTracker=codec.createTracker();return cpuTracker}
  function cpuReset(){cpuTracker=null;cpuSnapshot=null;cpuReadState=null;renderCpu(null)}
  function cpuLabel(value){return value===null||value===undefined?'Unavailable':value}
  function cpuSummaryText(){if(!cpuSnapshot)return 'CPU load unavailable.';if(cpuSnapshot.state==='valid')return 'CPU load '+cpuSnapshot.percentage.toFixed(1)+'% over '+cpuSnapshot.intervalSeconds.toFixed(1)+'s.';if(cpuSnapshot.state==='warming')return 'CPU load warming up (no complete sampling interval yet).';return 'CPU load unavailable.'}
  function renderCpu(state){var home=node('dashboardCpu'),detail=node('diagnosticsCpu');if(!home||!detail)return;if(state&&state.state==='valid'){home.textContent=state.percentage.toFixed(1)+'%';detail.textContent='Last CPU measurement: '+state.percentage.toFixed(1)+'%, measured over '+state.intervalSeconds.toFixed(1)+' seconds at '+capturedTime(state.capturedAt)+'. Experimental measurement; awaiting verification on the router.'}else if(state&&state.state==='warming'){home.textContent='Warming up';detail.textContent='Waiting for the next CPU sample. The measurement updates with device data.'}else{home.textContent='Unavailable';detail.textContent='CPU measurement is unavailable. Refresh device data to try again.'}}

  function ussdOwner(owner){if(owner!=='console'||routerOwner!==owner||!session)throw fault('E_USSD_SESSION','USSD requires a verified session and its operation lock.')}
  function ussdDocument(reply){if(!reply.body.length||reply.body.length>6144||/[^\x09\x0a\x0d\x20-\x7e]/.test(reply.body)||/<!|&/.test(reply.body)||/<\?/.test(reply.body.replace(/^\s*<\?xml\s[^?]*\?>/,'')))throw fault('E_USSD_RESPONSE','Invalid USSD response.',reply.requestId);return parseXml(reply.body,reply.requestId)}
  function engineeringExtension(){return w.MF885Community047Dev18Engineering||null}
  function engineeringOwner(owner){if(!session||routerOwner!==owner||(owner!=='engineering-read'&&owner!=='engineering-write'))throw fault('E_ENGINEERING_SESSION','Engineering operation requires a verified session and its operation lock.')}
  function engineeringDocument(reply){if(!reply.body.length||reply.body.length>32768||/<!DOCTYPE|<!ENTITY/i.test(reply.body))throw fault('E_ENGINEERING_RESPONSE','Invalid Engineering response.',reply.requestId);return parseXml(reply.body,reply.requestId)}
  function ttlExtension(){return w.MF885Community047Dev18TTL||null}
  function ttlTransportOwner(owner){if(!session||routerOwner!==owner||(owner!=='ttl-read'&&owner!=='ttl-write'))throw fault('E_TTL_SESSION','TTL operation requires a verified session and its operation lock.')}
  function ttlDocument(reply){if(!reply.body.length||reply.body.length>4096||/[^\x09\x0a\x0d\x20-\x7e]/.test(reply.body)||/<!|&/.test(reply.body)||/<\?/.test(reply.body.replace(/^\s*<\?xml\s[^?]*\?>/,'')))throw fault('E_TTL_RESPONSE','Invalid TTL response.',reply.requestId);return parseXml(reply.body,reply.requestId)}
  function request(options){
    return new Promise(function(resolve,reject){
      var xhr=new w.XMLHttpRequest(),settled=false,requestId=nextRequestId(),method=options.method||'GET',requestOwner=options.owner||'direct',requestEpochAtStart=requestEpoch,meta={method:method,route:safeRoute(options.url),owner:requestOwner},started=Date.now();
      if(routerOwner!==null&&requestOwner!==routerOwner){var conflict=fault('E_ROUTER_BUSY','Another router operation is already running.',requestId,meta);logFailure(conflict);reject(conflict);return}
      currentRequest={xhr:xhr,owner:requestOwner,requestId:requestId};
      if(w.console&&typeof w.console.debug==='function')privateLog('debug','[MF885]['+requestId+'] request start',meta);
      function finish(error){if(settled)return;settled=true;var stale=requestEpochAtStart!==requestEpoch;if(currentRequest&&currentRequest.xhr===xhr)currentRequest=null;if(stale&&(!error||error.mfCode!=='E_SESSION_EXPIRED'))error=staleFault(requestId,meta);meta.elapsedMs=Math.max(0,Date.now()-started);meta.status=Number(xhr.status)||0;var rawBody='',rawReadError='';try{rawBody=xhr.responseText||''}catch(readError){rawReadError=String(readError&&readError.message||readError);reportUnexpected('raw-response-read',readError)}if(w.console&&typeof w.console.debug==='function')privateLog('debug','[MF885]['+requestId+'] raw router response',{method:method,route:meta.route,owner:requestOwner,status:meta.status,elapsedMs:meta.elapsedMs,bodyCharacters:rawBody.length,bodyRedacted:true,responseReadFailed:!!rawReadError});if(error){var value=attachFault(error,'E_CLIENT',requestId,meta);logFailure(value);reject(value)}else{if(w.console&&typeof w.console.debug==='function')privateLog('debug','[MF885]['+requestId+'] request complete',meta);resolve({status:xhr.status,body:rawBody,auth:xhr.getResponseHeader('WWW-Authenticate')||'',requestId:requestId,meta:meta})}}
      try{xhr.open(method,options.url,true);xhr.timeout=options.timeoutMs||REQUEST_TIMEOUT_MS;xhr.setRequestHeader('Cache-Control','no-store, no-cache, must-revalidate');xhr.setRequestHeader('Pragma','no-cache');if(options.authorization)xhr.setRequestHeader('Authorization',options.authorization);if(options.body)xhr.setRequestHeader('Content-Type',options.contentType||'text/xml;charset=UTF-8');if(options.headers)for(var headerName in options.headers)if(Object.prototype.hasOwnProperty.call(options.headers,headerName))xhr.setRequestHeader(headerName,options.headers[headerName]);xhr.onload=function(){if(requestEpochAtStart!==requestEpoch){finish(staleFault(requestId,meta));return}if(xhr.status===200||(options.acceptStatuses&&options.acceptStatuses.indexOf(xhr.status)>=0)){if(currentRequest&&currentRequest.xhr===xhr)currentRequest=null;var expired=options.authorization&&requestOwner!=='login'?classifyReply(requestEpochAtStart,xhr.status,!!options.authorization,xhr.responseText,requestId,meta):null;finish(expired||undefined)}else if(xhr.status===401&&options.authorization&&requestOwner!=='login'){if(currentRequest&&currentRequest.xhr===xhr)currentRequest=null;finish(classifyReply(requestEpochAtStart,401,true,xhr.responseText,requestId,meta))}else finish(fault('E_HTTP','Router HTTP '+xhr.status+'.',requestId,meta))};xhr.onerror=function(){finish(fault('E_NETWORK','The router connection failed.',requestId,meta))};xhr.ontimeout=function(){finish(fault('E_TIMEOUT','The router did not answer within '+Math.round(xhr.timeout/1000)+' seconds.',requestId,meta))};xhr.onabort=function(){finish(fault('E_CANCELLED','Request cancelled.',requestId,meta))};if(w.console&&typeof w.console.debug==='function')privateLog('debug','[MF885]['+requestId+'] router request variables',{method:method,route:meta.route,owner:requestOwner,timeoutMs:xhr.timeout,bodyPresent:!!options.body,bodyCharacters:options.body?String(options.body).length:0});xhr.send(options.body||null)}catch(error){finish(attachFault(error,'E_CLIENT',requestId,meta))}
    });
  }
  function cancelCurrent(owner){if(!currentRequest)return false;if(owner&&currentRequest.owner!==owner){showError('messagesStatus',fault('E_CANCEL_OWNER','The active request belongs to another router operation.',currentRequest.requestId,{expectedOwner:owner,actualOwner:currentRequest.owner}),'Cancellation blocked.');return false}try{currentRequest.xhr.abort();return true}catch(error){var id=reportUnexpected('request.abort',error);status('messagesStatus','Request cancellation failed. [E_CANCEL_FAILED · '+id+']',true);return false}}
  function cancelMessages(){if(routerOwner!=='messages-read')return cancelCurrent('messages-read');if(!messagesCancelError){var id=currentRequest&&currentRequest.owner==='messages-read'?currentRequest.requestId:nextErrorId();messagesCancelError=fault('E_CANCELLED','Messages read cancelled.',id,{owner:'messages-read',phase:currentRequest?'active-request':'between-requests'});logFailure(messagesCancelError)}if(currentRequest&&currentRequest.owner==='messages-read')return cancelCurrent('messages-read');status('messagesStatus',errorText(messagesCancelError),true);return true}
  function modelUrl(name){if(ENDPOINTS.indexOf(name)<0)throw new Error('Unsupported router model.');return '/xml_action.cgi?method=get&module=duster&file='+encodeURIComponent(name)}
  function modelGet(name,owner){var operationEpoch=requestEpoch;return request({method:'GET',url:modelUrl(name),authorization:nextHeader('GET'),owner:owner,expiryCheck:true}).then(function(reply){if(operationEpoch!==requestEpoch)throw staleFault();try{var doc=parseXml(reply.body,reply.requestId);doc.mfMeta=reply.meta;return doc}catch(error){throw attachFault(error,'E_XML_INVALID',reply.requestId,reply.meta)}})}

  function login(password){
    var loginToken=beginRouterOperation('login','loginStatus');if(!loginToken)return Promise.resolve(null);var acceptedIdentity=null;var loginEpoch=requestEpoch;
    status('loginStatus','Request 1 of 3: asking for a login challenge…');node('signIn').disabled=true;
    return request({method:'GET',url:'/login.cgi',owner:'login'}).then(function(challengeReply){
      if(challengeReply.body.trim())throw fault('E_LOGIN_RESPONSE','The login challenge body was not empty.',challengeReply.requestId);
      var challenge=parseChallenge(challengeReply.auth,challengeReply.requestId),ha1=w.hex_md5('admin:'+challenge.realm+':'+password),queryProof=proof(challenge,ha1,'GET','/cgi/protected.cgi',1),header=digestHeader(challenge,ha1,'GET',1);
      var query='realm='+encodeURIComponent(challenge.realm)+'&nonce='+encodeURIComponent(challenge.nonce)+'&response='+queryProof.response+'&qop=auth&cnonce='+queryProof.cnonce+'&Action=Digest&username=admin&temp=marvell';
      status('loginStatus','Request 2 of 3: signing in…');
      return request({method:'GET',url:'/login.cgi?'+query,authorization:header,owner:'login'}).then(function(loginReply){
        if(/unauthorized|<login_status>\s*(?:UNAUTHORIZED|TIMEOUT|KICKOFF)/i.test(loginReply.body))throw fault('E_LOGIN_REJECTED','The router rejected the password.',loginReply.requestId);
        session={challenge:challenge,ha1:ha1,nc:2};
        status('loginStatus','Request 3 of 3: verifying this MF885…');return modelGet('status1','login');
      });
    }).then(function(identity){
      if(!exactIdentity(identity))throw fault('E_IDENTITY','The exact MF885 / Ver.D / 2.5.94 identity was not proven.',identity.mfRequestId);
      password='';acceptedIdentity=identity;requestEpoch=loginEpoch+1;expiryHandled=0;node('login').hidden=true;node('app').hidden=false;showPage(requestedPage());status('loginStatus','MF885 sign-in complete. Core controls are ready.');
      return identity;
    }).catch(function(error){session=null;showError('loginStatus',error,'Sign in failed.');throw error}).finally(function(){node('signIn').disabled=false;endRouterOperation('login',loginToken);if(acceptedIdentity)startAuthenticatedUi(acceptedIdentity)});
  }

  function validPage(name){return /^(?:dashboard|messages|diagnostics|modem|ttl|ussd|at)$/.test(String(name||''))}
  function requestedPage(){var name=String(w.location.hash||'').replace(/^#/,'');return validPage(name)?name:'dashboard'}
  function showPage(name,fromHash){name=validPage(name)?name:'dashboard';activePage=name;var pages=w.document.querySelectorAll('.page');for(var i=0;i<pages.length;i++)pages[i].hidden=pages[i].id!=='page-'+name;var buttons=w.document.querySelectorAll('[data-page]');for(var j=0;j<buttons.length;j++)buttons[j].classList.toggle('active',buttons[j].getAttribute('data-page')===name);if(!fromHash&&w.location.hash!=='#'+name)w.location.hash=name;if(diagnosticsSnapshot&&(name==='diagnostics'||name==='modem'))renderSnapshot(diagnosticsSnapshot)}
  function renderValues(id,rows){var root=node(id);root.textContent='';for(var i=0;i<rows.length;i++){var box=w.document.createElement('div'),label=w.document.createElement('span'),value=w.document.createElement('strong');box.className='value';label.textContent=rows[i][0];value.textContent=rows[i][1]||'Not returned';box.appendChild(label);box.appendChild(value);if(rows[i][2]){var source=w.document.createElement('small');source.className='value-source';source.textContent=rows[i][2];box.appendChild(source)}root.appendChild(box)}}
  function pathValue(doc,path){var current=doc&&doc.documentElement;if(!current)return null;for(var i=0;i<path.length;i++){var items=children(current,path[i]);if(items.length!==1)return null;current=items[0]}var value=String(current.textContent||'').trim();return value===''?null:value}
  function picked(snapshot,candidates){for(var i=0;i<candidates.length;i++){var candidate=candidates[i],entry=snapshot.endpoints[candidate[0]];if(!entry||!entry.ok)continue;var value=pathValue(entry.doc,candidate[1]);if(value!==null)return {raw:value,source:candidate[0]+' · '+candidate[1].join('/')}}return {raw:null,source:candidates.length?candidates[0][0]:'router'}}
  function engineer(snapshot,paths){var candidates=[];for(var i=0;i<paths.length;i++)candidates.push(['Engineer_parameter',paths[i]]);return picked(snapshot,candidates)}
  function mappedValue(item,map,suffix){if(item.raw===null)return {value:'Not returned',source:item.source};var value=Object.prototype.hasOwnProperty.call(map,item.raw)?map[item.raw]:'Unknown (raw '+item.raw+')';return {value:value+(suffix||''),source:item.source}}
  function directValue(item,suffix){return {value:item.raw===null?'Not returned':item.raw+(suffix||''),source:item.source}}
  function row(label,item){return [label,item.value,'Source: '+item.source]}
  function reportNumber(raw){if(raw===null||!/^[-+]?\d+(?:\.\d+)?$/.test(String(raw)))return null;var value=Number(raw);return Number.isFinite(value)?value:null}
  function decimal(value){return String(Math.round(value*10)/10)}
  function rsrpValue(item){var value=reportNumber(item.raw),display='Not returned';if(value!==null){if(value<0)display=decimal(value)+' dBm';else if(value===0)display='< -140 dBm · index 0';else if(value===97)display='>= -44 dBm · index 97';else if(value>0&&value<97)display=decimal(value-140)+' dBm · index '+value;else display='Unknown (raw '+item.raw+')'}return {value:display,source:item.source}}
  function rsrqValue(item){var value=reportNumber(item.raw),display='Not returned';if(value!==null){if(value<0)display=decimal(value)+' dB';else if(value===0)display='< -19.5 dB · index 0';else if(value===34)display='>= -3 dB · index 34';else if(value>0&&value<34)display=decimal(-19.5+(value*.5))+' dB · index '+value;else display='Unknown (raw '+item.raw+')'}return {value:display,source:item.source}}
  function rawRadioValue(item){return {value:item.raw===null?'Not returned':'raw '+item.raw,source:item.source}}
  function connectionTime(snapshot){var day=picked(snapshot,[['status1',['lan','run_days']]]),hour=picked(snapshot,[['status1',['lan','run_hours']]]),minute=picked(snapshot,[['status1',['lan','run_minutes']]]),second=picked(snapshot,[['status1',['lan','run_seconds']]]);if(day.raw===null&&hour.raw===null&&minute.raw===null&&second.raw===null)return {value:'Not returned',source:'status1 · lan/run_*'};return {value:(day.raw||'0')+'d '+(hour.raw||'0')+'h '+(minute.raw||'0')+'m '+(second.raw||'0')+'s',source:'status1 · lan/run_*'}}
  function diagnosticsRows(snapshot){
    var identity=snapshot.endpoints.status1&&snapshot.endpoints.status1.ok&&exactIdentity(snapshot.endpoints.status1.doc)?{value:'MF885 · Ver.D · 2.5.94',source:'status1 · sysinfo'}:{value:'Not proven',source:'status1 · sysinfo'};
    var sim=mappedValue(picked(snapshot,[['status1',['wan','cellular','sim_status']],['wan',['wan','cellular','sim_status']]]),{'0':'Ready','1':'Absent'});
    var registration=mappedValue(picked(snapshot,[['status1',['wan','NW_register_status']],['wan',['wan','NW_register_status']]]),{'0':'Not registered','1':'Registered · home','2':'Searching','3':'Registration denied','5':'Registered · roaming'});
    var battery=directValue(picked(snapshot,[['status1',['batteryinfo','Battery_percent']]]),'%');
    var batteryState=directValue(picked(snapshot,[['status1',['batteryinfo','Battery_status']]]));
    var charger=directValue(picked(snapshot,[['status1',['batteryinfo','Charger_status']]]));
    var output=directValue(picked(snapshot,[['status1',['batteryinfo','Output_current']]]));
    var engineeringMode=mappedValue(picked(snapshot,[['wan',['wan','Engineering_mode']]]),{'0':'Disabled','1':'Enabled'});
    return [row('Exact device identity',identity),row('SIM',sim),row('Network registration',registration),row('Battery level',battery),row('Battery state · raw',batteryState),row('Charger state · raw',charger),row('Output current · raw',output),row('Engineering collection',engineeringMode),row('Device uptime',connectionTime(snapshot))];
  }
  function modemRows(snapshot){
    var rat=mappedValue(picked(snapshot,[['status1',['wan','sys_mode']],['wan',['wan','sys_mode']]]),{'0':'No service','3':'2G','4':'3G','5':'3G','6':'4G · LTE','17':'4G · LTE'});
    var operator=directValue(picked(snapshot,[['status1',['wan','network_name']],['status1',['wan','ISP_name']],['wan',['wan','network_name']],['wan',['wan','ISP_name']]]));
    var band=directValue(engineer(snapshot,[['Engineer_parameter','LTE_band'],['Engineer_parameter','lte_band'],['Engineer_parameter','band'],['Engi','LTE','band'],['LTE','LTE_band'],['LTE','band']]));
    var earfcn=directValue(engineer(snapshot,[['Engineer_parameter','EARFCN'],['Engineer_parameter','earfcn'],['Engi','LTE','dlEuArfcn'],['LTE','EARFCN'],['LTE','dlEuArfcn']]));
    var pci=directValue(engineer(snapshot,[['Engineer_parameter','PCI'],['Engineer_parameter','pci'],['Engi','LTE','phyCellId'],['LTE','PCI'],['LTE','phyCellId']]));
    var cell=directValue(engineer(snapshot,[['Engineer_parameter','Cell_ID'],['Engineer_parameter','cell_id'],['Engineer_parameter','cellid'],['Engi','LTE','cellId'],['LTE','Cell_ID'],['LTE','cellId']]));
    var tac=directValue(engineer(snapshot,[['Engineer_parameter','TAC'],['Engineer_parameter','tac'],['Engineer_parameter','LAC'],['Engineer_parameter','lac'],['Engi','LTE','tac'],['LTE','TAC'],['LTE','tac']]));
    var rsrp=rsrpValue(engineer(snapshot,[['Engineer_parameter','RSRP'],['Engineer_parameter','rsrp'],['Engi','LTE','rsrp'],['LTE','RSRP'],['LTE','rsrp']]));
    var rsrq=rsrqValue(engineer(snapshot,[['Engineer_parameter','RSRQ'],['Engineer_parameter','rsrq'],['Engi','LTE','rsrq'],['LTE','RSRQ'],['LTE','rsrq']]));
    var sinr=rawRadioValue(engineer(snapshot,[['Engineer_parameter','SINR'],['Engineer_parameter','sinr'],['Engi','LTE','sinr'],['LTE','SINR'],['LTE','sinr']]));
    var rssi=rawRadioValue(engineer(snapshot,[['Engineer_parameter','RSSI'],['Engineer_parameter','rssi'],['Engi','LTE','rssi'],['LTE','RSSI'],['LTE','rssi']]));
    var signalIndex=directValue(picked(snapshot,[['status1',['wan','cellular','rssi']]]));
    return [row('Radio access',rat),row('Operator',operator),row('LTE band',band),row('DL EARFCN',earfcn),row('PCI',pci),row('Cell ID',cell),row('TAC / LAC',tac),row('RSRP',rsrp),row('RSRQ',rsrq),row('SINR',sinr),row('RSSI',rssi),row('Stock signal-quality index',signalIndex)];
  }
  function capturedTime(value){try{return new Date(value).toLocaleTimeString()}catch(error){var id=reportUnexpected('capture-time-format',error);return 'Unavailable ('+id+')'}}
  function wanRows(snapshot){
    var fields=[['WAN IPv4',['ipv4','ip','ip_address','wan_ip','IP_address']],['WAN IPv6',['ipv6','ipv6_address','wan_ipv6','IPv6_address']],['Gateway',['gateway','v4gateway','ipv4_gateway','wan_gateway']],['Primary DNS',['dns1','v4dns1','primary_dns']],['Secondary DNS',['dns2','v4dns2','secondary_dns']],['Configured APN',['apn','configured_apn','lte_apn']],['Active APN',['active_apn','current_apn','used_apn','wan_apn']],['Subnet mask',['mask']],['MTU',['mtu']],['WAN link state · raw',['wan_link_status']],['WAN connection state · raw',['wan_conn_status']],['PDP type · raw',['pdp_type']],['Connection state · raw',['connect_disconnect']],['Connection mode · raw',['connect_mode']],['Radio preference · raw',['prefer_mode']]];
    var rows=fields.map(function(field){var candidates=[];['wan','status1'].forEach(function(model){field[1].forEach(function(key){candidates.push([model,['wan',key]]);candidates.push([model,['wan','cellular',key]])})});return row(field[0],directValue(picked(snapshot,candidates)))});
    var entry=snapshot.endpoints.status1,doc=entry&&entry.ok?entry.doc:null;
    var roots=doc?children(doc.documentElement,'wan'):[],cells=roots.length===1?children(roots[0],'cellular'):[],lists=cells.length===1?children(cells[0],'pdp_context_list'):[],items=lists.length===1?children(lists[0],'Item'):[];
    items.slice(0,16).forEach(function(item,index){[['apn','APN'],['ipv4','IPv4'],['ipv6','IPv6'],['v4gateway','Gateway'],['v4dns1','Primary DNS'],['v4dns2','Secondary DNS']].forEach(function(field){var value=one(item,field[0]);if(value!==null&&value!=='')rows.push(['PDP '+(index+1)+' · '+field[1],value,'Source: status1 · wan/cellular/pdp_context_list/Item['+(index+1)+']/'+field[0]])})});
    return rows;
  }
  function renderWan(snapshot){var rows=wanRows(snapshot),available=rows.filter(function(r){return r[1]!=='Not returned'}),missing=rows.filter(function(r){return r[1]==='Not returned'});renderValues('wanValues',available.length?available:[['WAN','Not returned']]);renderValues('wanMissingValues',missing);node('wanMissing').hidden=missing.length===0;}

  function renderSources(id,snapshot){var root=node(id);root.textContent='';for(var i=0;i<ENDPOINTS.length;i++){var name=ENDPOINTS[i],entry=snapshot.endpoints[name],card=w.document.createElement('article'),title=w.document.createElement('strong'),detail=w.document.createElement('span'),timing=w.document.createElement('small');card.className='source-card '+(entry&&entry.ok?'ok':'failed');title.textContent=name;if(entry&&entry.ok)detail.textContent='OK · '+entry.requestId;else detail.textContent='Failed · '+(entry?entry.errorCode+' · '+entry.requestId:'not attempted');var age=entry?Math.max(0,Math.floor((Date.now()-entry.capturedAt)/1000)):0;timing.textContent=entry?entry.elapsedMs+' ms · '+capturedTime(entry.capturedAt)+' · '+age+'s since HTTP read':'No capture';card.appendChild(title);card.appendChild(detail);card.appendChild(timing);root.appendChild(card)}}
  function namedRow(rows,label){for(var i=0;i<rows.length;i++)if(rows[i][0]===label)return rows[i][1];return 'Not returned'}
  function renderDashboardSnapshot(snapshot,successes){var diagnostic=diagnosticsRows(snapshot),modem=modemRows(snapshot),registration=namedRow(diagnostic,'Network registration'),operator=namedRow(modem,'Operator'),battery=namedRow(diagnostic,'Battery level');node('dashboardNetwork').textContent=operator!=='Not returned'?operator:registration;node('dashboardBattery').textContent=battery;status('dashboardStatus','Device data '+successes+'/3 sources · '+capturedTime(snapshot.completedAt)+' · automatic universal refresh '+(liveEnabled?'on':'off')+'.',successes!==3)}
  function renderSnapshot(snapshot){var successes=0,failures=[];for(var i=0;i<ENDPOINTS.length;i++){var entry=snapshot.endpoints[ENDPOINTS[i]];if(entry&&entry.ok)successes++;else if(entry)failures.push(ENDPOINTS[i]+' '+entry.errorCode+' · '+entry.requestId)}renderValues('diagnosticsValues',diagnosticsRows(snapshot));renderValues('modemValues',modemRows(snapshot));renderWan(snapshot);renderSources('diagnosticsSources',snapshot);renderCpu(snapshot.cpu||null);var summary='Snapshot '+snapshot.id+' · '+successes+'/3 device endpoints · '+capturedTime(snapshot.completedAt)+'.';if(failures.length)summary+=' '+failures.join(' · ');summary+=' '+cpuSummaryText();if(liveEnabled)summary+=' Next universal device refresh in 30 seconds.';status('diagnosticsStatus',summary,successes!==3);status('modemStatus',summary,successes!==3);node('modemFreshness').textContent='Shared snapshot '+snapshot.id+' · read at '+capturedTime(snapshot.completedAt)+' · radio measurement time unknown. Source details are in Diagnostics.';renderDashboardSnapshot(snapshot,successes)}
  function setSnapshotControls(busy){snapshotBusy=busy;syncRouterControls()}
  function readSnapshot(seedStatus1,trigger){var operationEpoch=requestEpoch;
    if(snapshotBusy)return Promise.resolve(diagnosticsSnapshot);var snapshotToken=beginRouterOperation('snapshot','diagnosticsStatus');if(!snapshotToken)return Promise.resolve(diagnosticsSnapshot);setSnapshotControls(true);var snapshot={id:nextSnapshotId(),startedAt:Date.now(),completedAt:null,trigger:trigger||'manual',endpoints:{}},index=0;if(seedStatus1&&exactIdentity(seedStatus1)){var seedMeta=seedStatus1.mfMeta||{};snapshot.endpoints.status1={ok:true,doc:seedStatus1,requestId:seedStatus1.mfRequestId||'ERR46-UNKNOWN',elapsedMs:Number(seedMeta.elapsedMs)||0,capturedAt:Date.now(),reusedFromLogin:true};index=1}if(w.console&&typeof w.console.debug==='function')privateLog('debug','[MF885]['+snapshot.id+'] snapshot variables',{trigger:snapshot.trigger,status1Reused:index===1,endpointCount:ENDPOINTS.length,automaticRetryCeiling:0});
    function next(){if(operationEpoch!==requestEpoch)throw staleFault();if(index>=ENDPOINTS.length)return Promise.resolve();var name=ENDPOINTS[index++],progress='Snapshot '+snapshot.id+' · reading '+name+' ('+index+' of 3)…';status('diagnosticsStatus',progress);status('modemStatus',progress);return modelGet(name,'snapshot').then(function(doc){if(operationEpoch!==requestEpoch)throw staleFault();var meta=doc.mfMeta||{};snapshot.endpoints[name]={ok:true,doc:doc,requestId:doc.mfRequestId||'ERR46-UNKNOWN',elapsedMs:Number(meta.elapsedMs)||0,capturedAt:Date.now()};if(w.console&&typeof w.console.debug==='function')privateLog('debug','[MF885]['+snapshot.id+'] endpoint complete',{endpoint:name,ok:true,requestId:doc.mfRequestId||'',elapsedMs:Number(meta.elapsedMs)||0})},function(error){if(operationEpoch!==requestEpoch)throw staleFault();var value=logFailure(error,name+' read failed.'),meta=value.mfMeta||{};snapshot.endpoints[name]={ok:false,requestId:value.mfId||nextErrorId(),errorCode:value.mfCode||'E_CLIENT',elapsedMs:Number(meta.elapsedMs)||0,capturedAt:Date.now()};if(w.console&&typeof w.console.debug==='function')privateLog('debug','[MF885]['+snapshot.id+'] endpoint complete',{endpoint:name,ok:false,requestId:snapshot.endpoints[name].requestId,errorCode:snapshot.endpoints[name].errorCode,elapsedMs:snapshot.endpoints[name].elapsedMs})}).then(next)}
    function readCpu(){cpuTransportOwner('snapshot');var codec=cpuExtension();if(!codec){cpuReadState='module-unavailable';cpuSnapshot={state:'unavailable'};return Promise.resolve(null)}status('diagnosticsStatus','Snapshot '+snapshot.id+' · reading CPU load…');return request({method:'GET',url:'/xml_action.cgi?method=get&module=duster&file=c047d18cpu',authorization:nextHeader('GET'),owner:'snapshot',expiryCheck:true}).then(function(reply){if(operationEpoch!==requestEpoch)throw staleFault();return cpuDocument(reply)}).then(function(wire){if(operationEpoch!==requestEpoch)throw staleFault();var tracker=cpuTrackerInstance();if(!tracker){cpuReadState='module-unavailable';cpuSnapshot={state:'unavailable'};return null}var state=tracker.observe(wire);cpuReadState=state.state;cpuSnapshot=state;return null},function(error){if(operationEpoch!==requestEpoch)throw staleFault();if(cpuTracker)cpuTracker.reset();cpuReadState='unavailable';cpuSnapshot={state:'unavailable'};if(w.console&&typeof w.console.debug==='function')privateLog('debug','[MF885]['+snapshot.id+'] CPU read failed',{endpoint:'cpu',errorCode:error&&error.mfCode||'E_CPU_UNAVAILABLE'});return null})}
    return next().then(function(){if(operationEpoch!==requestEpoch)throw staleFault();return readCpu()}).then(function(){if(operationEpoch!==requestEpoch)throw staleFault();snapshot.cpu=cpuSnapshot;snapshot.completedAt=Date.now();diagnosticsSnapshot=snapshot;nextSnapshotAt=Date.now()+SNAPSHOT_POLL_MS;renderSnapshot(snapshot);return snapshot}).catch(function(error){if(operationEpoch!==requestEpoch)return null;showError('diagnosticsStatus',error,'Shared snapshot unavailable.');showError('modemStatus',error,'Shared snapshot unavailable.');throw error}).finally(function(){if(operationEpoch!==requestEpoch)return;setSnapshotControls(false);endRouterOperation('snapshot',snapshotToken)});
  }


  function xmlDocument(payload){return XML_DECLARATION+payload}
  function smsRequestXml(folder,page){return xmlDocument('<RGW><message><flag><message_flag>'+escapeXml(folder.flag)+'</message_flag></flag><get_message><page_number>'+page+'</page_number></get_message></message></RGW>')}
  function decodeUcs2(value){var source=String(value||'').trim();if(!/^(?:[0-9a-fA-F]{4})+$/.test(source))return source;var output='';for(var i=0;i<source.length;i+=4)output+=String.fromCharCode(parseInt(source.slice(i,i+4),16));return output}
  function messageIdMeta(value){var raw=String(value||''),parts=raw.split(','),trailingComma=raw.slice(-1)===',';if(trailingComma)parts.pop();var nonempty=parts.length>0,partCountWithinLimit=parts.length<=MAX_MESSAGE_ID_PARTS,rawLengthWithinLimit=raw.length<=MAX_MESSAGE_ID_CHARACTERS,tokensSafe=nonempty,partsUnique=nonempty,seen=Object.create(null);for(var i=0;i<parts.length;i++){var token=parts[i];if(!/^[A-Za-z0-9_-]{1,64}$/.test(token))tokensSafe=false;var key='$'+token;if(seen[key])partsUnique=false;seen[key]=true}var grammarSafe=nonempty&&partCountWithinLimit&&rawLengthWithinLimit&&tokensSafe&&partsUnique,canonical=grammarSafe?parts.join(',')+',':'';return {raw:raw,rawLength:raw.length,rawLengthLimit:MAX_MESSAGE_ID_CHARACTERS,rawLengthWithinLimit:rawLengthWithinLimit,parts:parts,partCount:parts.length,partLimit:MAX_MESSAGE_ID_PARTS,partCountWithinLimit:partCountWithinLimit,trailingComma:trailingComma,nonempty:nonempty,tokensSafe:tokensSafe,partsUnique:partsUnique,grammarSafe:grammarSafe,canonical:canonical,deleteValue:canonical}}
  function messageFlowLog(requestId,kind,values){if(w.console&&typeof w.console.debug==='function')privateLog('debug','[MF885]['+(requestId||'MSG29-FINAL')+'] messages '+kind,values||{})}
  function parseSmsPage(doc){var requestId=doc.mfRequestId||'';var containers=doc.getElementsByTagName('get_message');if(containers.length!==1||containers[0].getElementsByTagName('message_list').length!==1)throw fault('E_MESSAGES_RESPONSE','Unexpected Messages response.',requestId);var items=containers[0].getElementsByTagName('Item'),result=[];for(var i=0;i<items.length;i++){var from=decodeUcs2(text(items[i],'from')).replace(/^;/,'').replace(/;.*$/,''),recipient=decodeUcs2(text(items[i],'contacts')||text(items[i],'to')||text(items[i],'from')).replace(/^;/,'').replace(/;.*$/,'');result.push({id:text(items[i],'index'),from:from,recipient:recipient,body:decodeUcs2(text(items[i],'subject')||text(items[i],'content')),date:text(items[i],'received')})}var total=parseInt(text(containers[0],'total_number'),10);return {items:result,pages:Number.isFinite(total)&&total>0?total:null,requestId:requestId}}
  function smsPage(folder,page,owner){var operationEpoch=requestEpoch;var body=smsRequestXml(folder,page);return request({method:'POST',url:'/xml_action.cgi?method=set&module=duster&file=message',authorization:nextHeader('POST'),body:body,owner:owner,expiryCheck:true}).then(function(){if(operationEpoch!==requestEpoch)throw staleFault();return request({method:'GET',url:'/xml_action.cgi?method=get&module=duster&file=message',authorization:nextHeader('GET'),owner:owner,expiryCheck:true})}).then(function(reply){if(operationEpoch!==requestEpoch)throw staleFault();return parseSmsPage(parseXml(reply.body,reply.requestId))})}
  function readFolderData(folderKey,onProgress,owner){var operationEpoch=requestEpoch;
    var folder=FOLDERS[folderKey],all=[],reportedPages=null,page=1,seen=Object.create(null),ids=Object.create(null),tokens=Object.create(null),lastRequestId='';
    function next(){if(operationEpoch!==requestEpoch)throw staleFault();
      if(owner==='messages-read'&&messagesCancelError)throw messagesCancelError;
      if(page>MAX_MESSAGE_PAGES)throw fault('E_MESSAGES_LIMIT','Stopped at the 20-page safety limit.');
      var currentPage=page;return smsPage(folder,currentPage,owner).then(function(result){if(operationEpoch!==requestEpoch)throw staleFault();
        lastRequestId=result.requestId;var pageCountStable=currentPage===1||result.pages===null||result.pages===reportedPages;if(currentPage===1)reportedPages=result.pages;else if(!pageCountStable)throw fault('E_MESSAGES_CHANGED','The router changed the page count during the read.',result.requestId);
        var fingerprint=result.items.map(function(item){return [item.id,item.from,item.date,item.body].join('\u001f')}).join('\u001e'),fingerprintKey='$'+fingerprint,pageRepeated=!!(fingerprint&&seen[fingerprintKey]);messageFlowLog(result.requestId,'page conditions',{folder:folderKey,page:currentPage,reportedPages:reportedPages,observedPages:result.pages,pageCountStable:pageCountStable,itemCount:result.items.length,fingerprintPresent:!!fingerprint,pageRepeated:pageRepeated});if(pageRepeated)throw fault('E_MESSAGES_REPEATED_PAGE','The router repeated a page.',result.requestId);if(fingerprint)seen[fingerprintKey]=true;
        for(var i=0;i<result.items.length;i++){var id=String(result.items[i].id||''),meta=messageIdMeta(id),identity=meta.grammarSafe?meta.canonical:meta.raw,idKey='$'+identity;ids[idKey]=(ids[idKey]||0)+1;for(var part=0;part<meta.parts.length;part++){var tokenKey='$'+meta.parts[part];tokens[tokenKey]=(tokens[tokenKey]||0)+1}result.items[i].idMeta=meta;result.items[i].sourcePage=currentPage;result.items[i].sourceOrdinal=i+1}
        all=all.concat(result.items);if(onProgress)onProgress(all.slice(),currentPage);
        var emptyPage=!result.items.length,emptyHistoryAllowed=emptyPage&&currentPage===1&&(reportedPages===null||reportedPages===1),prematureEmpty=emptyPage&&!emptyHistoryAllowed&&reportedPages!==null&&currentPage<=reportedPages,stopReported=reportedPages!==null&&currentPage>=reportedPages,stopShort=reportedPages===null&&result.items.length<10,stopEmpty=emptyPage;messageFlowLog(result.requestId,'page stop conditions',{emptyPage:emptyPage,emptyHistoryAllowed:emptyHistoryAllowed,prematureEmpty:prematureEmpty,stopByReportedPages:stopReported,stopByShortPage:stopShort,stopByEmptyPage:stopEmpty,continueToNextPage:!(prematureEmpty||stopReported||stopShort||stopEmpty)});if(prematureEmpty)throw fault('E_MESSAGES_INCOMPLETE','The router returned an empty page before the reported history ended.',result.requestId);if(stopReported||stopShort||stopEmpty)return;
        page++;return new Promise(function(resolve){w.setTimeout(resolve,0)}).then(function(){if(operationEpoch!==requestEpoch)throw staleFault();if(owner==='messages-read'&&messagesCancelError)throw messagesCancelError;return next()});
      })
    }
    return next().then(function(){if(operationEpoch!==requestEpoch)throw staleFault();var mutationIdsSafe=true;for(var i=0;i<all.length;i++){var item=all[i],meta=item.idMeta||messageIdMeta(item.id),identity=meta.grammarSafe?meta.canonical:meta.raw,occurrences=ids['$'+identity]||0,tokenOccurrences=[],tokensUnique=true;for(var part=0;part<meta.parts.length;part++){var count=tokens['$'+meta.parts[part]]||0;tokenOccurrences.push(count);if(count!==1)tokensUnique=false}item.deleteSafe=meta.grammarSafe&&occurrences===1&&tokensUnique;if(!item.deleteSafe)mutationIdsSafe=false;messageFlowLog(lastRequestId, 'ID condition',{folder:folderKey,page:item.sourcePage,ordinal:item.sourceOrdinal,rawId:meta.raw,rawLength:meta.rawLength,rawLengthLimit:meta.rawLengthLimit,rawLengthWithinLimit:meta.rawLengthWithinLimit,canonicalId:meta.canonical,partCount:meta.partCount,partLimit:meta.partLimit,partCountWithinLimit:meta.partCountWithinLimit,trailingComma:meta.trailingComma,nonempty:meta.nonempty,tokensSafe:meta.tokensSafe,partsUnique:meta.partsUnique,recordOccurrences:occurrences,recordUnique:occurrences===1,tokenOccurrences:tokenOccurrences,tokensGloballyUnique:tokensUnique,mutationSafe:item.deleteSafe})}messageFlowLog(lastRequestId, 'folder result',{folder:folderKey,itemCount:all.length,complete:true,mutationIdsSafe:mutationIdsSafe});return {items:all,complete:true,mutationIdsSafe:mutationIdsSafe,requestId:lastRequestId}});
  }
  function prepareMessagePreview(result,folderKey,trigger){var ids=Object.create(null),tokens=Object.create(null),items=result.items,complete=result.pages===1||(result.pages===null&&items.length<10)||items.length===0,mutationIdsSafe=complete;for(var i=0;i<items.length;i++){var meta=messageIdMeta(items[i].id),identity=meta.grammarSafe?meta.canonical:meta.raw;items[i].idMeta=meta;items[i].sourcePage=1;items[i].sourceOrdinal=i+1;ids['$'+identity]=(ids['$'+identity]||0)+1;for(var part=0;part<meta.parts.length;part++)tokens['$'+meta.parts[part]]=(tokens['$'+meta.parts[part]]||0)+1}for(var index=0;index<items.length;index++){var item=items[index],itemMeta=item.idMeta,recordIdentity=itemMeta.grammarSafe?itemMeta.canonical:itemMeta.raw,recordUnique=ids['$'+recordIdentity]===1,tokensUnique=true;for(var token=0;token<itemMeta.parts.length;token++)if(tokens['$'+itemMeta.parts[token]]!==1)tokensUnique=false;item.deleteSafe=complete&&itemMeta.grammarSafe&&recordUnique&&tokensUnique;if(!item.deleteSafe)mutationIdsSafe=false;messageFlowLog(result.requestId,'preview ID condition',{trigger:trigger,folder:folderKey,page:1,ordinal:item.sourceOrdinal,rawId:itemMeta.raw,rawLength:itemMeta.rawLength,rawLengthWithinLimit:itemMeta.rawLengthWithinLimit,partCount:itemMeta.partCount,partCountWithinLimit:itemMeta.partCountWithinLimit,trailingComma:itemMeta.trailingComma,tokensSafe:itemMeta.tokensSafe,partsUnique:itemMeta.partsUnique,recordUnique:recordUnique,tokensGloballyUnique:tokensUnique,completeHistory:complete,mutationSafe:item.deleteSafe})}messageFlowLog(result.requestId,'preview result',{trigger:trigger,folder:folderKey,itemCount:items.length,reportedPages:result.pages,completeHistory:complete,mutationIdsSafe:mutationIdsSafe});return {items:items,complete:complete,mutationIdsSafe:mutationIdsSafe,requestId:result.requestId,reportedPages:result.pages}}
  function loadMessagesPreview(trigger){var operationEpoch=requestEpoch;
    if(mutationBusy||mutationLocked||messagesBusy)return Promise.resolve(null);var previewToken=beginRouterOperation('messages-preview','messagesStatus');if(!previewToken)return Promise.resolve(null);var folderKey=node('folder').value;setMessageControls(true);status('messagesStatus','Loading the newest '+FOLDERS[folderKey].label.toLowerCase()+' page…');messageFlowLog('', 'preview variables',{trigger:trigger||'manual',folder:folderKey,pageCeiling:1,semanticPostCeiling:1,resultGetCeiling:1,automaticRetryCeiling:0});
    return smsPage(FOLDERS[folderKey],1,'messages-preview').then(function(result){if(operationEpoch!==requestEpoch)throw staleFault();var preview=prepareMessagePreview(result,folderKey,trigger||'manual');messages=preview.items;messagesComplete=preview.complete;messagesMutationSafe=preview.mutationIdsSafe;messagePage=1;lastMessagesAt=Date.now();nextMessagesAt=lastMessagesAt+MESSAGES_POLL_MS;renderMessages();node('dashboardMessages').textContent=String(messages.length)+(messagesComplete?' total':' newest');var summary=messages.length+' message'+(messages.length===1?'':'s')+' on the newest page · '+capturedTime(lastMessagesAt)+'.';if(!messagesComplete)summary+=' Complete history is not loaded; use “Load complete history”.';if(liveEnabled)summary+=' Next universal message refresh in 60 seconds.';status('messagesStatus',summary,!messagesMutationSafe&&messagesComplete);return preview}).catch(function(error){if(operationEpoch!==requestEpoch)return null;messagesComplete=false;messagesMutationSafe=false;showError('messagesStatus',error,'Latest messages unavailable.');node('dashboardMessages').textContent='Unavailable';return null}).finally(function(){if(operationEpoch!==requestEpoch)return;setMessageControls(false);endRouterOperation('messages-preview',previewToken)})
  }
  function setMessageControls(busy){messagesBusy=busy;syncRouterControls()}
  function loadMessages(){var operationEpoch=requestEpoch;
    if(mutationBusy||mutationLocked)return Promise.resolve();var readToken=beginRouterOperation('messages-read','messagesStatus');if(!readToken)return Promise.resolve();messagesCancelError=null;
    var folderKey=node('folder').value;messagesComplete=false;messagesMutationSafe=false;setMessageControls(true);status('messagesStatus','Reading page 1…');
    return readFolderData(folderKey,function(all,page){messages=all;messagePage=1;renderMessages();status('messagesStatus','Loaded '+all.length+' messages; completed page '+page+'…')},'messages-read').then(function(result){if(operationEpoch!==requestEpoch)throw staleFault();messages=result.items;messagesComplete=true;messagesMutationSafe=result.mutationIdsSafe;messagePage=1;lastMessagesAt=Date.now();nextMessagesAt=lastMessagesAt+MESSAGES_POLL_MS;renderMessages();node('dashboardMessages').textContent=String(messages.length)+' total';var summary=messages.length+' message'+(messages.length===1?'':'s')+'. Complete bounded read.';if(liveEnabled)summary+=' Latest-page live refresh remains on.';if(!messagesMutationSafe)summary+=' One or more message IDs overlap, repeat, or are unsafe; Delete is disabled for this folder. Send uses its own complete Sent-history preflight.';status('messagesStatus',summary,!messagesMutationSafe)}).catch(function(error){if(operationEpoch!==requestEpoch)return null;messagesComplete=false;messagesMutationSafe=false;showError('messagesStatus',error,'Messages unavailable.')}).finally(function(){if(operationEpoch!==requestEpoch)return;setMessageControls(false);endRouterOperation('messages-read',readToken)});
  }
  function renderMessages(){var root=node('messagesList');root.textContent='';var pages=Math.max(1,Math.ceil(messages.length/DISPLAY_PAGE_SIZE)),folder=FOLDERS[node('folder').value];messagePage=Math.max(1,Math.min(messagePage,pages));if(!messages.length){var empty=w.document.createElement('p');empty.className='empty';empty.textContent='No messages.';root.appendChild(empty)}else{var start=(messagePage-1)*DISPLAY_PAGE_SIZE,end=Math.min(messages.length,start+DISPLAY_PAGE_SIZE);for(var i=start;i<end;i++){var article=w.document.createElement('article'),head=w.document.createElement('div'),sender=w.document.createElement('strong'),date=w.document.createElement('time'),body=w.document.createElement('div');article.className='message';head.className='message-head';sender.textContent=messages[i].from||'Unknown sender';date.textContent=messages[i].date||'Date not returned';body.className='message-body';body.textContent=messages[i].body;head.appendChild(sender);head.appendChild(date);article.appendChild(head);article.appendChild(body);if(folder.deletable&&messagesComplete&&messagesMutationSafe&&messages[i].deleteSafe){var button=w.document.createElement('button');button.type='button';button.className='danger';button.textContent='Delete';button.setAttribute('data-delete-id',messages[i].id);button.disabled=routerOwner!==null||mutationBusy||mutationLocked;button.addEventListener('click',function(){deleteMessage(this.getAttribute('data-delete-id'))});article.appendChild(button)}root.appendChild(article)}}node('messagesPager').hidden=messages.length<=DISPLAY_PAGE_SIZE;node('messagesPage').textContent='Page '+messagePage+' of '+pages;node('messagesPrevious').disabled=messagePage<=1;node('messagesNext').disabled=messagePage>=pages}

  function encodeUcs2(value){var output='';for(var i=0;i<value.length;i++)output+=('0000'+value.charCodeAt(i).toString(16)).slice(-4);return output.toUpperCase()}
  function validPhone(value){return /^\+?[0-9]{3,15}$/.test(String(value||''))}
  function validBody(value){value=String(value||'');if(!value.length||value.length>MAX_SMS_UNITS)return false;for(var i=0;i<value.length;i++){var code=value.charCodeAt(i);if((code>=0xd800&&code<=0xdfff)||code===0||(code>=0x7f&&code<=0x9f)||(code<0x20&&code!==10&&code!==13))return false}return true}
  function segments(value){var length=String(value||'').length;return length?length<=70?1:Math.ceil(length/67):0}
  function smsTime(date){date=date||new Date();var year=String(date.getFullYear()).slice(2),zone=0-date.getTimezoneOffset()/60,zoneText=zone>0?'%2B'+zone:'-'+zone;return [year,date.getMonth()+1,date.getDate(),date.getHours(),date.getMinutes(),date.getSeconds(),zoneText].join(',')}
  function commandState(doc){var command=text(doc,'sms_cmd'),result=text(doc,'sms_cmd_status_result');return {command:command,result:result,complete:result==='3',pending:result===''||result==='0'||result==='1'}}
  function pollCommand(command,attempt,owner){var operationEpoch=requestEpoch;return request({method:'GET',url:'/xml_action.cgi?method=get&module=duster&file=message',authorization:nextHeader('GET'),owner:owner,expiryCheck:true}).then(function(reply){if(operationEpoch!==requestEpoch)throw staleFault();var value=commandState(parseXml(reply.body,reply.requestId));if(value.command===String(command)&&value.complete)return;if(value.command===String(command)&&!value.pending)throw fault('E_COMMAND_REJECTED','Router rejected command '+command+' with status '+value.result+'.',reply.requestId);if(attempt>=STATUS_POLLS-1)throw fault('E_COMMAND_UNPROVEN','Command completion was not proven.',reply.requestId);return new Promise(function(resolve){w.setTimeout(resolve,1000)}).then(function(){if(operationEpoch!==requestEpoch)throw staleFault();return pollCommand(command,attempt+1,owner)})})}
  function postMutation(body,command,owner){var operationEpoch=requestEpoch;return request({method:'POST',url:'/xml_action.cgi?method=set&module=duster&file=message',authorization:nextHeader('POST'),body:body,owner:owner,expiryCheck:true}).then(function(){if(operationEpoch!==requestEpoch)throw staleFault();return pollCommand(command,0,owner)})}
  function lockUnknown(error){var value=logFailure(error,'Mutation verification failed.');if(value.mfCode==='E_SESSION_EXPIRED'||value.mfCode==='E_STALE_SESSION'){return}mutationLocked=true;mutationBusy=false;setMessageControls(false);renderMessages();status('messagesStatus',errorText(value)+' Outcome unknown; reload the page before another write.',true)}
  function sendXml(number,body,date){return xmlDocument('<RGW><message><flag><message_flag>SEND_SMS</message_flag><sms_cmd>4</sms_cmd></flag><send_save_message><contacts>'+escapeXml(number)+'</contacts><content>'+encodeUcs2(body)+'</content><encode_type>UNICODE</encode_type><sms_time>'+smsTime(date)+'</sms_time></send_save_message></message></RGW>')}
  function deleteXml(id){var folder=FOLDERS.inbox,meta=messageIdMeta(id);if(!meta.grammarSafe)throw fault('E_DELETE_ID','The selected message ID is not safe to submit.');return xmlDocument('<RGW><message><flag><message_flag>DELETE_SMS</message_flag><sms_cmd>6</sms_cmd></flag><get_message><tags>'+folder.tags+'</tags><mem_store>'+folder.store+'</mem_store></get_message><set_message><delete_message_id>'+escapeXml(meta.deleteValue)+'</delete_message_id></set_message></message></RGW>')}
  function sendMessage(event){var operationEpoch=requestEpoch;
    event.preventDefault();if(mutationBusy||mutationLocked)return;var target=String(node('messageNumber').value||'').trim(),body=String(node('messageBody').value||'');if(!validPhone(target)){status('messagesStatus','Use 3–15 digits and an optional leading +. Nothing sent.',true);return}if(!validBody(body)){status('messagesStatus','Use 1–268 BMP characters without emoji or control characters. Nothing sent.',true);return}var sendToken=beginRouterOperation('messages-send','messagesStatus');if(!sendToken)return;
    mutationBusy=true;setMessageControls(true);status('messagesStatus','Reading the complete Sent baseline before submission…');var beforeTokens=Object.create(null),submitted=false;
    readFolderData('sent',null,'messages-send').then(function(before){if(operationEpoch!==requestEpoch)throw staleFault();if(!before.mutationIdsSafe)throw fault('E_SEND_BASELINE_IDS','Sent history contains an unsafe, repeated, or overlapping message ID.',before.requestId);for(var i=0;i<before.items.length;i++)for(var part=0;part<before.items[i].idMeta.parts.length;part++)beforeTokens['$'+before.items[i].idMeta.parts[part]]=true;messageFlowLog(before.requestId, 'send baseline',{items:before.items.length,uniqueTokens:Object.keys(beforeTokens).length,mutationIdsSafe:before.mutationIdsSafe});status('messagesStatus','Submitting exactly one Send request…');submitted=true;return postMutation(sendXml(target,body),4,'messages-send')}).then(function(){if(operationEpoch!==requestEpoch)throw staleFault();status('messagesStatus','Send accepted; verifying the complete Sent folder…');return readFolderData('sent',null,'messages-send')}).then(function(after){if(operationEpoch!==requestEpoch)throw staleFault();if(!after.mutationIdsSafe){lockUnknown(fault('E_SEND_READBACK_IDS','Sent readback contains an unsafe, repeated, or overlapping message ID.',after.requestId));return}var matched=false;for(var i=0;i<after.items.length;i++){var item=after.items[i],allTokensNew=true;for(var part=0;part<item.idMeta.parts.length;part++)if(beforeTokens['$'+item.idMeta.parts[part]])allTokensNew=false;if(allTokensNew&&item.recipient===target&&item.body===body){matched=true;break}}if(!matched){lockUnknown(fault('E_SEND_READBACK','No matching record with entirely new message-ID tokens was found.',after.requestId));return}mutationBusy=false;setMessageControls(false);node('messageComposer').hidden=true;node('messageNumber').value='';node('messageBody').value='';node('messageCount').textContent='0 / '+MAX_SMS_UNITS+' · 0 of 4 UCS-2 segments';status('messagesStatus','Recorded in Sent. Delivery is not proven. No retry was sent.')}).catch(function(error){if(operationEpoch!==requestEpoch)return null;if(submitted)lockUnknown(error);else{mutationBusy=false;setMessageControls(false);showError('messagesStatus',error,'Sent baseline failed.',' Nothing was submitted.')}}).finally(function(){if(operationEpoch!==requestEpoch)return;endRouterOperation('messages-send',sendToken)})
  }
  function deleteMessage(id){var operationEpoch=requestEpoch;
    var meta=messageIdMeta(id),matches=0;for(var index=0;index<messages.length;index++)if(messages[index].id===meta.raw&&messages[index].deleteSafe)matches++;var preflightGreen=!mutationBusy&&!mutationLocked&&messagesComplete&&messagesMutationSafe&&node('folder').value==='inbox'&&meta.grammarSafe&&matches===1;messageFlowLog('', 'delete preflight',{rawId:meta.raw,grammarSafe:meta.grammarSafe,matches:matches,messagesComplete:messagesComplete,messagesMutationSafe:messagesMutationSafe,mutationBusy:mutationBusy,mutationLocked:mutationLocked,folder:node('folder').value,passed:preflightGreen});if(!preflightGreen){showError('messagesStatus',fault('E_DELETE_PRECONDITION','Delete preconditions were not proven.'),'Nothing was deleted.');return}if(!w.confirm('Delete this SMS? This cannot be undone.'))return;var deleteToken=beginRouterOperation('messages-delete','messagesStatus');if(!deleteToken)return;
    mutationBusy=true;setMessageControls(true);status('messagesStatus','Submitting exactly one Delete request…');var submitted=true;
    postMutation(deleteXml(meta.raw),6,'messages-delete').then(function(){if(operationEpoch!==requestEpoch)throw staleFault();status('messagesStatus','Delete accepted; verifying the complete inbox…');return readFolderData('inbox',null,'messages-delete')}).then(function(after){if(operationEpoch!==requestEpoch)throw staleFault();if(!after.mutationIdsSafe){lockUnknown(fault('E_DELETE_READBACK_IDS','Inbox readback contains an unsafe, repeated, or overlapping message ID.',after.requestId));return}var survivingTokens=[];for(var i=0;i<after.items.length;i++)for(var part=0;part<after.items[i].idMeta.parts.length;part++)if(meta.parts.indexOf(after.items[i].idMeta.parts[part])>=0)survivingTokens.push(after.items[i].idMeta.parts[part]);messageFlowLog(after.requestId,'delete readback',{submittedTokens:meta.parts,survivingTokens:survivingTokens,allSubmittedTokensAbsent:survivingTokens.length===0});if(survivingTokens.length){lockUnknown(fault('E_DELETE_READBACK','At least one submitted message-ID token is still present.',after.requestId,{survivingTokens:survivingTokens}));return}messages=after.items;messagesComplete=true;messagesMutationSafe=true;messagePage=1;mutationBusy=false;setMessageControls(false);renderMessages();status('messagesStatus','Deleted and verified absent. No retry was sent.')}).catch(function(error){if(operationEpoch!==requestEpoch)return null;if(submitted)lockUnknown(error);else showError('messagesStatus',error,'Delete failed before submission. Nothing was deleted.')}).finally(function(){if(operationEpoch!==requestEpoch)return;endRouterOperation('messages-delete',deleteToken)})
  }

  function updateLiveControl(){var target=node('liveToggle'),visible=w.document.visibilityState!=='hidden';target.setAttribute('aria-pressed',liveEnabled?'true':'false');target.textContent=liveEnabled?(visible?'Auto refresh · on':'Auto refresh · paused'):'Auto refresh · off'}
  function stopLive(){if(liveTimer!==null){w.clearTimeout(liveTimer);liveTimer=null}updateLiveControl()}
  function universalDueAt(){var snapshotDue=nextSnapshotAt||Date.now(),messagesDue=nextMessagesAt||Date.now();return Math.min(snapshotDue,messagesDue)}
  function scheduleLive(delay){if(liveTimer!==null){w.clearTimeout(liveTimer);liveTimer=null}if(!session||!liveEnabled)return;var wait=delay===undefined?Math.max(0,universalDueAt()-Date.now()):Math.max(0,Number(delay)||0);liveTimer=w.setTimeout(runLiveTick,Math.min(wait,Math.max(SNAPSHOT_POLL_MS,MESSAGES_POLL_MS)))}
  function skippedLiveStatus(id,reason){var text='Universal refresh deferred: '+reason+' · '+id+'. No request or retry was sent.';status('dashboardStatus',text,true);if(activePage==='messages')status('messagesStatus',text,true);else if(activePage==='diagnostics')status('diagnosticsStatus',text,true);else if(activePage==='modem')status('modemStatus',text,true)}
  function runLiveTick(){var operationEpoch=requestEpoch;liveTimer=null;if(!session||!liveEnabled)return Promise.resolve(null);var id=nextLiveId(),now=Date.now(),visible=w.document.visibilityState!=='hidden',ownerFree=routerOwner===null,mutationFree=!mutationBusy,messageDue=now>=(nextMessagesAt||0),snapshotDue=now>=(nextSnapshotAt||0),messageAllowed=!mutationLocked;liveLog(id,'variables',{activePage:activePage,refreshScope:'all-safe-data',visible:visible,routerOwner:routerOwner,mutationBusy:mutationBusy,mutationLocked:mutationLocked,messageDue:messageDue,snapshotDue:snapshotDue,nextMessagesAt:nextMessagesAt,nextSnapshotAt:nextSnapshotAt,automaticRetryCeiling:0});liveCondition(id,'session_present',true,!!session,!!session);liveCondition(id,'live_enabled',true,liveEnabled,liveEnabled);liveCondition(id,'document_visible',true,visible,visible);liveCondition(id,'router_owner_free',true,ownerFree,ownerFree);liveCondition(id,'mutation_idle',true,mutationFree,mutationFree);liveCondition(id,'universal_refresh_due',true,messageDue||snapshotDue,messageDue||snapshotDue);liveCondition(id,'message_state_allows_preview',true,messageAllowed,messageAllowed);if(!visible||!ownerFree||!mutationFree){var reason=!visible?'tab hidden':!ownerFree?'router operation '+routerOwner+' active':'message mutation active';liveLog(id,'terminal',{terminal_reason:'UNIVERSAL_REFRESH_DEFERRED',reason:reason,requestCount:0,retryCount:0});if(visible)skippedLiveStatus(id,reason);if(visible)scheduleLive(1000);return Promise.resolve(null)}var flow=Promise.resolve(),dispatchCount=0;if(snapshotDue){dispatchCount++;nextSnapshotAt=now+SNAPSHOT_POLL_MS;liveLog(id,'dispatch',{kind:'shared-snapshot',getCeiling:4,cpuGetCeiling:1});flow=flow.then(function(){if(operationEpoch!==requestEpoch)throw staleFault();return readSnapshot(null,'live:'+id)}).catch(function(error){if(operationEpoch!==requestEpoch)return null;logFailure(error,'Universal device refresh failed.');return null})}if(messageDue&&messageAllowed){dispatchCount++;nextMessagesAt=now+MESSAGES_POLL_MS;liveLog(id,'dispatch',{kind:'messages-preview',semanticPostCeiling:1,resultGetCeiling:1});flow=flow.then(function(){if(operationEpoch!==requestEpoch)throw staleFault();return session?loadMessagesPreview('live:'+id):null})}else if(messageDue){nextMessagesAt=now+MESSAGES_POLL_MS;liveLog(id,'messages skipped',{reason:'message outcome locked',requestCount:0,retryCount:0})}if(!dispatchCount)liveLog(id,'terminal',{terminal_reason:'UNIVERSAL_REFRESH_NOT_DUE',requestCount:0,retryCount:0});return flow.catch(function(error){if(operationEpoch===requestEpoch)logFailure(error,'Live refresh stopped.');return null}).finally(function(){if(operationEpoch!==requestEpoch)return;scheduleLive()})}
  function refreshAll(trigger){var operationEpoch=requestEpoch;if(!session)return Promise.resolve(null);var id=nextLiveId(),ownerFree=routerOwner===null,mutationFree=!mutationBusy,messageAllowed=!mutationLocked;liveLog(id,'manual universal refresh variables',{trigger:trigger||'manual',routerOwner:routerOwner,mutationBusy:mutationBusy,mutationLocked:mutationLocked,ownerFree:ownerFree,mutationFree:mutationFree,messageAllowed:messageAllowed,automaticRetryCeiling:0});liveCondition(id,'router_owner_free',true,ownerFree,ownerFree);liveCondition(id,'mutation_idle',true,mutationFree,mutationFree);liveCondition(id,'message_state_allows_preview',true,messageAllowed,messageAllowed);if(!ownerFree||!mutationFree){skippedLiveStatus(id,!ownerFree?'router operation '+routerOwner+' active':'message mutation active');return Promise.resolve(null)}return readSnapshot(null,(trigger||'manual')+':'+id).catch(function(error){if(operationEpoch!==requestEpoch)return null;logFailure(error,'Universal device refresh failed.');return null}).then(function(){if(operationEpoch!==requestEpoch)throw staleFault();if(!messageAllowed||!session)return null;return loadMessagesPreview((trigger||'manual')+':'+id)}).catch(function(error){if(operationEpoch!==requestEpoch)return null;logFailure(error,'Universal device refresh stopped.');return null}).finally(function(){if(operationEpoch!==requestEpoch)return;scheduleLive()})}
  function setLiveEnabled(value){liveEnabled=!!value;try{if(w.sessionStorage)w.sessionStorage.setItem('mf885-c047d18-live',liveEnabled?'1':'0')}catch(error){reportUnexpected('live-preference-write',error)}updateLiveControl();var id=nextLiveId();liveLog(id,'preference',{enabled:liveEnabled,refreshScope:'all-safe-data'});if(liveEnabled){nextMessagesAt=0;nextSnapshotAt=0;scheduleLive(0)}else stopLive()}
  function startAuthenticatedUi(identity){var operationEpoch=requestEpoch;bootstrapBusy=true;stopLive();nextSnapshotAt=0;nextMessagesAt=0;status('dashboardStatus','Signed in. Loading device data and the newest inbox page…');var first=activePage==='messages'?loadMessagesPreview('bootstrap'):readSnapshot(identity,'bootstrap'),second=activePage==='messages'?function(){return readSnapshot(identity,'bootstrap')}:function(){return loadMessagesPreview('bootstrap')};first.then(function(){if(operationEpoch!==requestEpoch)return null;return second()}).catch(function(error){if(operationEpoch!==requestEpoch)return null;showError('dashboardStatus',error,'Automatic first load did not complete.');return null}).finally(function(){if(operationEpoch!==requestEpoch)return;bootstrapBusy=false;nextSnapshotAt=Date.now()+SNAPSHOT_POLL_MS;nextMessagesAt=Date.now()+MESSAGES_POLL_MS;if(diagnosticsSnapshot)renderDashboardSnapshot(diagnosticsSnapshot,ENDPOINTS.filter(function(name){return diagnosticsSnapshot.endpoints[name]&&diagnosticsSnapshot.endpoints[name].ok}).length);scheduleLive()})}

  function finishLocalLogout(message,error){requestEpoch++;expiryHandled=1;operationToken++;routerOwner=null;cancelCurrent();session=null;stopLive();syncRouterControls();var ttl=ttlExtension();if(ttl)ttl.reset();var engineering=engineeringExtension();if(engineering)engineering.reset();var ussd=w.MF885Community047Dev18Console;if(ussd)ussd.reset();messages=[];messagesComplete=false;messagesMutationSafe=false;mutationBusy=false;mutationLocked=false;diagnosticsSnapshot=null;snapshotBusy=false;bootstrapBusy=false;nextSnapshotAt=0;nextMessagesAt=0;lastMessagesAt=null;cpuReset();['diagnosticsValues','modemValues','wanValues','wanMissingValues','diagnosticsSources','messagesList','dashboardNetwork','dashboardBattery','dashboardMessages','modemFreshness'].forEach(function(id){var element=node(id);if(element)element.textContent=''});['password','messageNumber','messageBody','ussdCode','atCommand'].forEach(function(id){var element=node(id);if(element)element.value=''});messagesBusy=false;messagesCancelError=null;node('messageComposer').hidden=true;node('app').hidden=true;node('login').hidden=false;status('loginStatus',message||'Signed out. No automatic request will run.',!!error);node('password').focus()}
  function logout(){if(routerOwner!==null)return;finishLocalLogout()}

  function bind(){
    try{var preference=w.sessionStorage&&w.sessionStorage.getItem('mf885-c047d18-live');liveEnabled=preference===null||preference===undefined||preference==='1'}catch(error){liveEnabled=true;reportUnexpected('live-preference-read',error)}node('boot').hidden=true;node('login').hidden=false;updateLiveControl();
    node('loginForm').addEventListener('submit',function(event){event.preventDefault();var password=node('password').value;login(password).catch(function(error){if(!error||!error.mfLogged)reportUnexpected('login-submit',error)}).finally(function(){node('password').value=''})});
    var links=w.document.querySelectorAll('[data-page]');for(var i=0;i<links.length;i++)links[i].addEventListener('click',function(event){event.preventDefault();showPage(this.getAttribute('data-page'))});
    node('logout').addEventListener('click',logout);node('liveToggle').addEventListener('click',function(){setLiveEnabled(!liveEnabled)});node('refreshAll').addEventListener('click',function(){refreshAll('manual-header')});
    node('diagnosticsRefresh').addEventListener('click',function(){refreshAll('manual-diagnostics')});node('modemRefresh').addEventListener('click',function(){refreshAll('manual-modem')});
    node('messagesRefresh').addEventListener('click',loadMessages);node('messagesCancel').addEventListener('click',cancelMessages);node('messagesNew').addEventListener('click',function(){if(!mutationBusy&&!mutationLocked&&routerOwner===null){node('messageComposer').hidden=false;node('messageNumber').focus()}});node('messageDiscard').addEventListener('click',function(){if(!mutationBusy&&routerOwner===null)node('messageComposer').hidden=true});node('messageComposer').addEventListener('submit',sendMessage);node('messageBody').addEventListener('input',function(){var length=String(this.value||'').length,parts=segments(this.value);node('messageCount').textContent=length+' / '+MAX_SMS_UNITS+' · '+parts+' of 4 UCS-2 segment'+(parts===1?'':'s')});node('folder').addEventListener('change',function(){messages=[];messagesComplete=false;messagesMutationSafe=false;messagePage=1;node('folderTitle').textContent=FOLDERS[this.value].label;renderMessages();status('messagesStatus','Loading the newest page automatically…');nextMessagesAt=0;if(session&&liveEnabled)scheduleLive(0)});
    node('messagesPrevious').addEventListener('click',function(){if(messagePage>1){messagePage--;renderMessages()}});node('messagesNext').addEventListener('click',function(){if(messagePage<Math.ceil(messages.length/DISPLAY_PAGE_SIZE)){messagePage++;renderMessages()}});
    w.addEventListener('hashchange',function(){if(session)showPage(requestedPage(),true)});w.document.addEventListener('visibilitychange',function(){updateLiveControl();var id=nextLiveId(),visible=w.document.visibilityState!=='hidden';liveLog(id,'visibility',{visible:visible,refreshScope:'all-safe-data'});if(session&&liveEnabled&&visible){nextMessagesAt=0;nextSnapshotAt=0;scheduleLive(0)}else if(!visible)stopLive()});
    syncRouterControls();
  }
  if(w.addEventListener){w.addEventListener('error',function(event){reportUnexpected('window.error',event&&event.error?event.error:event)});w.addEventListener('unhandledrejection',function(event){reportUnexpected('unhandledrejection',event&&event.reason?event.reason:event)})}
  w.MF885Community047Dev18={version:VERSION,timeoutMs:REQUEST_TIMEOUT_MS,snapshotPollMs:SNAPSHOT_POLL_MS,messagesPollMs:MESSAGES_POLL_MS,maxMessagePages:MAX_MESSAGE_PAGES,maxMessageIdParts:MAX_MESSAGE_ID_PARTS,maxMessageIdCharacters:MAX_MESSAGE_ID_CHARACTERS,statusPolls:STATUS_POLLS,xmlDeclaration:XML_DECLARATION,parseChallenge:parseChallenge,parseXml:parseXml,exactIdentity:exactIdentity,parseSmsPage:parseSmsPage,messageIdMeta:messageIdMeta,request:request,login:login,cancel:cancelCurrent,validPhone:validPhone,validBody:validBody,segments:segments,encodeUcs2:encodeUcs2,smsTime:smsTime,smsRequestXml:smsRequestXml,sendXml:sendXml,deleteXml:deleteXml,commandState:commandState,errorText:errorText,reportUnexpected:reportUnexpected,pathValue:pathValue,diagnosticsRows:diagnosticsRows,modemRows:modemRows,readSnapshot:readSnapshot,loadMessagesPreview:loadMessagesPreview,refreshAll:refreshAll,runLiveTick:runLiveTick,setLiveEnabled:setLiveEnabled,powerBridge:{begin:beginRouterOperation,end:endRouterOperation,busy:function(){return routerOwner!==null},sessionPresent:function(){return session!==null},credentials:function(){if(routerOwner!=='power'||!session)throw fault('E_POWER_SESSION','Sign in first.');return {realm:session.challenge.realm,ha1:session.ha1}},proof:proof,parseChallenge:parseChallenge,parseXml:parseXml,exactIdentity:exactIdentity,stopLive:stopLive,finish:finishLocalLogout,currentEpoch:function(){return requestEpoch},expire:function(epoch,error){return expireSessionOnce(epoch,error)},release:function(owner,token){return endRouterOperation(owner,token)},classifyReply:classifyReply},wanRows:wanRows,consoleBridge:{begin:beginRouterOperation,end:endRouterOperation,sessionPresent:function(){return session!==null},routerBusy:function(){return routerOwner!==null},
    get:function(owner){ussdOwner(owner);return request({method:'GET',url:'/xml_action.cgi?method=get&module=duster&file=c047d18console',authorization:nextHeader('GET'),owner:owner,expiryCheck:true}).then(ussdDocument)},
    network:function(owner){ussdOwner(owner);return request({method:'GET',url:'/xml_action.cgi?method=get&module=duster&file=status1',authorization:nextHeader('GET'),owner:owner,expiryCheck:true}).then(ussdDocument)},
    post:function(value,owner){ussdOwner(owner);if(typeof value!=='string'||!/^[0-9a-f]{8}:[0-9a-f]{8}:[0-9a-f]{8}:[sau]:[0-9a-f]{0,448}$/.test(value))throw fault('E_USSD_VALUE','Invalid USSD request.');var body=XML_DECLARATION+'<RGW><diagnostic><console_v1>'+value+'</console_v1></diagnostic></RGW>';return request({method:'POST',url:'/xml_action.cgi?method=set&module=duster&file=c047d18console',authorization:nextHeader('POST'),body:body,owner:owner,timeoutMs:60000,expiryCheck:true}).then(function(){return null})}
  },engineeringBridge:{
    begin:beginRouterOperation,end:endRouterOperation,
    sessionPresent:function(){return session!==null},routerBusy:function(){return routerOwner!==null},
    get:function(owner){engineeringOwner(owner);return request({method:'GET',url:'/xml_action.cgi?method=get&module=duster&file=wan',authorization:nextHeader('GET'),owner:owner,expiryCheck:true}).then(engineeringDocument)},
    post:function(value,owner){engineeringOwner(owner);if(owner!=='engineering-write'||(value!=='0'&&value!=='1'))throw fault('E_ENGINEERING_VALUE','Invalid Engineering setting.');var body=XML_DECLARATION+'<RGW><wan><Engineering_mode>'+value+'</Engineering_mode>'+(value==='1'?'<query_time_interval>1</query_time_interval>':'')+'</wan></RGW>';return request({method:'POST',url:'/xml_action.cgi?method=set&module=duster&file=wan',authorization:nextHeader('POST'),body:body,owner:owner,timeoutMs:60000,expiryCheck:true}).then(function(reply){return reply.body?engineeringDocument(reply):null})}
  },ttlBridge:{
    begin:beginRouterOperation,end:endRouterOperation,
    sessionPresent:function(){return session!==null},routerBusy:function(){return routerOwner!==null},
    capability:function(owner){ttlTransportOwner(owner);return request({method:'GET',url:'/c047d18ttl.json',owner:owner}).then(function(reply){return reply.body})},
    get:function(owner){ttlTransportOwner(owner);return request({method:'GET',url:'/xml_action.cgi?method=get&module=duster&file=diagnostic',authorization:nextHeader('GET'),owner:owner,expiryCheck:true}).then(ttlDocument)},
    post:function(value,owner){ttlTransportOwner(owner);if(owner!=='ttl-write'||typeof value!=='string'||!/^(?:off|[1-9][0-9]{0,2})$/.test(value)||(value!=='off'&&(Number(value)<1||Number(value)>255)))throw fault('E_TTL_VALUE','Invalid TTL.');var body=XML_DECLARATION+'<RGW><diagnostic><command>ttl</command><arg>'+value+'</arg></diagnostic></RGW>';return request({method:'POST',url:'/xml_action.cgi?method=set&module=duster&file=diagnostic',authorization:nextHeader('POST'),body:body,owner:owner,expiryCheck:true}).then(ttlDocument)}
  }};
  if(w.document.readyState==='loading')w.document.addEventListener('DOMContentLoaded',bind);else bind();
})(window);
